### ISSUE TITLE
[Fastpitch/Pytorch] Error running on colab.

### ISSUE THREAD

**Issue by vonLeebpl** [NVIDIA/DeepLearningExamples#1032]
Hi,
I try to run FastPitch training on custom data set on colab.
I managed to install all dependencies and compile amp_C.
`train.py --help` gives no errors.
However when I try to prepare data set I got this:

```
!python ./prepare_dataset.py --wav-text-filelists {ds_path}/filelists/wav_list_train.txt  {ds_path}/filelists/wav_list_val.txt --n-workers 16 --batch-size 1 --dataset-path {ds_path} --extract-pitch

Processing /content/drive/MyDrive/voices/hugin/filelists/wav_list_train.txt...
Traceback (most recent call last):
  File "/content/DeepLearningExamples/PyTorch/SpeechSynthesis/FastPitch/prepare_dataset.py", line 174, in <module>
    main()
  File "/content/DeepLearningExamples/PyTorch/SpeechSynthesis/FastPitch/prepare_dataset.py", line 129, in main
    pitch_online_method=args.f0_method)
  File "/content/DeepLearningExamples/PyTorch/SpeechSynthesis/FastPitch/fastpitch/data_function.py", line 190, in __init__
    self.betabinomial_interpolator = BetaBinomialInterpolator()
  File "/content/DeepLearningExamples/PyTorch/SpeechSynthesis/FastPitch/fastpitch/data_function.py", line 54, in __init__
    self.bank = functools.lru_cache(beta_binomial_prior_distribution)
  File "/usr/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

Python version on colab is 3.7.12.

It looks like it's a kind of cache problem. Any suggestion to workaround it?

**Comment by vonLeebpl** [comment]
Duplicated, sorry
