### ISSUE TITLE
[Model/Framework] NaN returned from FastPitchLoss with AMP

### ISSUE THREAD

**Issue by brentcty-2020** [NVIDIA/DeepLearningExamples#1042]
Related to training the model

**Describe the bug**
Get a NaN back for loss from FastPitchLoss function when AMP is enabled

**To Reproduce**
Follow the setup instructions, but change amp=true (epoch 1, iter 324)

**Expected behavior**
DLL 2021-12-05 23:33:20.005016 - epoch    1 | iter 324/781 | loss  6.42 | mel loss  3.11 | kl loss 0.00908 | kl weight 0.01000 |   30481.56 frames/s | took 0.23 s | lrate 5.56e-03
Traceback (most recent call last):
  File "train.py", line 668, in <module>
    main()
  File "train.py", line 562, in main
    raise Exception("loss is NaN")
Exception: loss is NaN
Killing subprocess 2427
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train.py', '--local_rank=0', '--cuda', '-o', './output', '--log-file', './output/nvlog.json', '--dataset-path', 'LJSpeech-1.1', '--training-files', 'filelists/ljs_audio_pitch_text_train_v3.txt', '--validation-files', 'filelists/ljs_audio_pitch_text_val.txt', '-bs', '8', '--grad-accumulation', '2', '--optimizer', 'lamb', '--epochs', '100', '--epochs-per-checkpoint', '10', '--resume', '--warmup-steps', '100', '-lr', '0.1', '--weight-decay', '1e-6', '--grad-clip-thresh', '1000.0', '--dur-predictor-loss-scale', '0.1', '--pitch-predictor-loss-scale', '0.1', '--kl-loss-start-epoch', '0', '--kl-loss-warmup-epochs', '100', '--text-cleaners', 'english_cleaners_v2', '--n-speakers', '1', '--amp', '--p-arpabet', '1.0', '--energy-conditioning', '--seed', '1234', '--load-pitch-from-disk']' returned non-zero exit status 1.

**Environment**
Please provide at least:
* Ubuntu 20.04
* Container version python3, pytorch 1.9.0a0+2ecb2c7
* GPU: Nvidia GeForce RTX 2070 Super 
* Nvidia Driver: 470.86
* CUDA: 11.4

**Comment by brentcty-2020** [comment]
This issues seemed to go away when I changed the batch size from 8 to 12.
