### ISSUE TITLE
[Bert/PyTorch] A possible bug for LDDL

### ISSUE THREAD

**Issue by Hannibal046** [NVIDIA/DeepLearningExamples#1120]
Hi, a possible bug for LDDL. It works when using ` python -m torch.distributed.launch --nproc_per_node 2 `. But failed when using  `torch.multiprocessing.spawn`
```python
import argparse
import logging
import os
import lddl.torch
import torch.multiprocessing as mp

def main(local_rank=0):
    input_dir = '/home/hannibal046/project/BERT/data/pretrain/phase2/bin_size_64/parquet/'
    vocab_file = 'vocab/vocab'
    batch_size = 64 
    num_workers = 4
    start_epoch = 0
    epochs = 2
    print('local_rank',local_rank)
    train_dataloader = lddl.torch.get_bert_pretrain_data_loader(
    input_dir,
    local_rank=local_rank,
    vocab_file=vocab_file,
    data_loader_kwargs={
        'batch_size': batch_size,
        'num_workers': num_workers,
        'pin_memory': True,
    },
    log_level=logging.WARNING,
    start_epoch=start_epoch,
    )

    from tqdm import tqdm
    for epoch in range(start_epoch, start_epoch + epochs):
        for i, batch in enumerate(tqdm(train_dataloader)):
            pass

if __name__=='__main__':
    mp.spawn(main,nprocs=2)     
```
```
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    mp.spawn(main,nprocs=2)
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/hannibal046/project/mybert/src/test.py", line 30, in main
    for i, batch in enumerate(tqdm(train_dataloader)):
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/site-packages/lddl/torch/dataloader.py", line 52, in __iter__
    num_samples_remaining, dataiters = self._init_iter()
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/site-packages/lddl/torch/dataloader.py", line 31, in _init_iter
    dataiters = [iter(dl) for dl in self._dataloaders]
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/site-packages/lddl/torch/dataloader.py", line 31, in <listcomp>
    dataiters = [iter(dl) for dl in self._dataloaders]
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __iter__
    self._iterator = self._get_iterator()
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 927, in __init__
    w.start()
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/hannibal046/anaconda3/envs/bert/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function ParquetDataset.<lambda> at 0x7fce35b59280>: attribute lookup ParquetDataset.<lambda> on lddl.torch.datasets failed
```

But in this scripts ,`python -m torch.distributed.launch --nproc_per_node 2 test.py`works:
```python
import argparse
import logging
import os
import lddl.torch
import torch.multiprocessing as mp
parser = argparse.ArgumentParser()
parser.add_argument(
    '--local_rank',
    type=int,
    default=-1,
    # default=os.getenv('LOCAL_RANK', 0),
    # help='local_rank is set by torch.distributed.launch or SLURM',
)

def main():
    args = parser.parse_args()
    local_rank = args.local_rank
    input_dir = '/home/hannibal046/project/BERT/data/pretrain/phase2/bin_size_64/parquet/'
    vocab_file = 'vocab/vocab'
    batch_size = 64 
    num_workers = 4
    start_epoch = 0
    epochs = 2
    print('local_rank',local_rank)
    train_dataloader = lddl.torch.get_bert_pretrain_data_loader(
    input_dir,
    local_rank=local_rank,
    vocab_file=vocab_file,
    data_loader_kwargs={
        'batch_size': batch_size,
        'num_workers': num_workers,
        'pin_memory': True,
    },
    log_level=logging.WARNING,
    start_epoch=start_epoch,
    )

    from tqdm import tqdm
    for epoch in range(start_epoch, start_epoch + epochs):
        for i, batch in enumerate(tqdm(train_dataloader)):
            pass

if __name__=='__main__':
    main()     
```

**Comment by sharathts** [comment]
`torch.multiprocessing.spawn` is not something we support currently.
Will follow up in case there is an easy fix. Feel free to post in case you find a solution meanwhile.

**Comment by shangw-nvidia** [comment]
Hi, @Hannibal046 ,

The core issue is that the Python native `pickle` being used in `torch.multiprocessing.spawn` cannot pickle lambda and local functions, and it's not just `torch.multiprocessing` but rather `multiprocessing` in general ([reference](https://stackoverflow.com/questions/19984152/what-can-multiprocessing-and-dill-do-together)). There are two different ways to go about this problem:
1. Instead of `multiprocessing`, wrap around better library (e.g., `pathos.multiprocessing`) that actually supports pickling lambda functions. To me, this seems the right approach, since I don't see any fundamental reason why you must not pickle a lambda function in PyTorch.
2. Replace all the lambda and local functions in LDDL with statically defined function. I'd rather not go with this approach since it would make the code a lot uglier and more difficult to maintain (I mean, obviously, lambda function exists for a reason).

In any case, supporting `torch.multiprocessing.spawn` is not in our short term plan, and we recommend to use `torch.distributed.launch` to launch data-parallel distributed training (for perf reasons as well).

**Comment by Hannibal046** [comment]
Hi, @shangw-nvidia 
I got it! Thanks so much for insightful responses.
