### ISSUE TITLE
[DLRM/PyTorch] Not able to train on binary dataset

### ISSUE THREAD

**Issue by rakshithvasudev** [NVIDIA/DeepLearningExamples#1156]
Related to DLRM/PyTorch:

Sorry for this question. But I thought I'll ask it anyway. I'm trying to run the DLRM model with criteo terabyte dataset having bin version of dataset that is preprocessed. Its the same version of the preprocessed output when we run from the facebook dlrm repo:

```
python dlrm_s_pytorch.py --arch-sparse-feature-size=128 --arch-mlp-bot="13-512-256-128" \
       --arch-mlp-top="1024-1024-512-256-1" --max-ind-range=40000000 --data-generation=dataset \
       --data-set=terabyte --raw-data-file=/data/day --processed-data-file=/data/day --loss-function=bce \
       --round-targets=True --learning-rate=1.0 --mini-batch-size=2048 --print-freq=2048 --print-time \
       --test-freq=102400 --test-mini-batch-size=16384 --test-num-workers=16 --memory-map --mlperf-logging \
       --mlperf-auc-threshold=0.8025 --mlperf-bin-loader --mlperf-bin-shuffle \
       --mlperf-coalesce-sparse-grads --use-gpu
```

This would provide generate 2 files: "day_train.bin" and "day_test.bin" will be created. I noticed that in previous commits, this repo supported bin loader as seen here: https://github.com/NVIDIA/DeepLearningExamples/blob/7fe3d5be4f53eeb223cfd664b1d6b3f177745411/PyTorch/Recommendation/DLRM/dlrm/data/data_loader.py#L25

The commit in specific is https://github.com/NVIDIA/DeepLearningExamples/tree/7fe3d5be4f53eeb223cfd664b1d6b3f177745411/PyTorch/Recommendation/DLRM

Now, when I run the same command
`python -m dlrm.scripts.main --mode train --dataset /dataset/
`

I get the following error:
```
Epoch:[0/1] [200/128028]  eta: 1:33:19  loss: 0.1896  step_time: 0.043808  lr: 0.8794
Epoch:[0/1] [400/128028]  eta: 1:21:51  loss: 0.1364  step_time: 0.033153  lr: 1.7544
Epoch:[0/1] [600/128028]  eta: 1:17:44  loss: 0.1335  step_time: 0.032864  lr: 2.6294
Epoch:[0/1] [800/128028]  eta: 1:15:32  loss: 0.1332  step_time: 0.032689  lr: 3.5044
Epoch:[0/1] [1000/128028]  eta: 1:14:18  loss: 0.1371  step_time: 0.032997  lr: 4.3794
Epoch:[0/1] [1200/128028]  eta: 1:13:27  loss: 0.1425  step_time: 0.032985  lr: 5.2544
Epoch:[0/1] [1400/128028]  eta: 1:12:41  loss: 0.1426  step_time: 0.032632  lr: 6.1294
Epoch:[0/1] [1600/128028]  eta: 1:12:14  loss: 0.1363  step_time: 0.033134  lr: 7.0044
Epoch:[0/1] [1800/128028]  eta: 1:11:53  loss: 0.1330  step_time: 0.033262  lr: 7.8794
Epoch:[0/1] [2000/128028]  eta: 1:11:30  loss: 0.1328  step_time: 0.032933  lr: 8.7544
Epoch:[0/1] [2200/128028]  eta: 1:11:07  loss: 0.1302  step_time: 0.032649  lr: 9.6294
Epoch:[0/1] [2400/128028]  eta: 1:10:48  loss: 0.1304  step_time: 0.032724  lr: 10.5044
Epoch:[0/1] [2600/128028]  eta: 1:10:33  loss: 0.1306  step_time: 0.032983  lr: 11.3794
Epoch:[0/1] [2800/128028]  eta: 1:10:17  loss: 0.1306  step_time: 0.032694  lr: 12.2544
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [8,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [9,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [11,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [12,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [13,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [14,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [15,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [16,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [17,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [18,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [19,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [20,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [21,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [22,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [23,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [24,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [25,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [26,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [27,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [28,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [100,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [101,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [102,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [103,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [107,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [108,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [109,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
....
....
...
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [91,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [92,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [93,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [798,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/dlrm/DeepLearningExamples/PyTorch/Recommendation/DLRM/dlrm/scripts/main.py", line 568, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/workspace/dlrm/DeepLearningExamples/PyTorch/Recommendation/DLRM/dlrm/scripts/main.py", line 352, in main
    train(model, loss_fn, optimizer, data_loader_train, data_loader_test, scaled_lr)
  File "/workspace/dlrm/DeepLearningExamples/PyTorch/Recommendation/DLRM/dlrm/scripts/main.py", line 414, in train
    output = model(numerical_features, categorical_features).squeeze().float()
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/dlrm/DeepLearningExamples/PyTorch/Recommendation/DLRM/dlrm/model.py", line 220, in forward
    interaction_output = self._interaction(bottom_mlp_output, embedding_outputs, batch_size)
  File "/workspace/dlrm/DeepLearningExamples/PyTorch/Recommendation/DLRM/dlrm/model.py", line 125, in _interaction
    interaction_flat = interaction[:, self.tril_indices[0], self.tril_indices[1]]
RuntimeError: CUDA error: device-side assert triggered
```

**To Reproduce**
I'm running with the ngc container pytorch:22.06-py3 version and launching the job as follows:

`DeepLearningExamples# python -m dlrm.scripts.main --mode train --dataset /dataset/
`

**Expected behavior**
The training should resume as seen above without any error. 

**Code version**

https://github.com/NVIDIA/DeepLearningExamples/tree/7fe3d5be4f53eeb223cfd664b1d6b3f177745411/PyTorch/Recommendation/DLRM

**Environment**
* Container version (pytorch:22.06-py3):
* GPUs in the system: (8x A100-PCIE-40GB):
* CUDA driver version (e.g. 470.42.01):

For more context I also notice a similar thing when I train with facebook's DLRM repo. I opened an issue there as well. I know these two repos are not related. But for anyone interested, here is the [link ](https://github.com/facebookresearch/dlrm/issues/247)to the error. I'm of the opinion that a fix here might also be an fix there.

It may very well be the version mismatch. But I'd like to be run this code on the latest version of pytorch provided by the ngc container 22.06-py3. So I guess my question would be what would be some changes we need to do to this version of the code to run it on the latest container. 

Once again, sorry for this question. I understand the older version is not really the one to be asked about. But I had to seek an expert opinion :)

**Comment by tgrel** [comment]
Hi @rakshithvasudev. Do I understand correctly that you are using the dataset produced by the DLRM implementation maintained at: https://github.com/facebookresearch/dlrm? If yes, then this is unfortunately not going to work so easily. The format of the dataset is the same, that is correct, but the contents are slightly different. Preprocessing done in the facebookresearch implementation generates categorical features with quite large cardinality (up to 40M for some features IIRC). This cannot be trained on a singleGPU as you've attempted above.

You can try to train it using multiple GPUs, but this 1) is not tested by us and not recommended, and, 2) will be very slow because you use PCIe devices that are not well suited for model-parallel/hybrid-parallel training scenarios we're showcasing in the DLRM-PyT example.

My advice is to try to go through all the steps in our quickstart guide including our preprocessing. This way you'll be sure the code is tested by us and should work. Please let me know if this works for you.

**Comment by tgrel** [comment]
Closing due to lack of activity. Please reopen if you're still experiencing problems.
