### ISSUE TITLE
[SE3Transformer/pytorch] Crash in some settings of the SE3Transformer example

### ISSUE THREAD

**Issue by aosokin** [NVIDIA/DeepLearningExamples#1204]
If the [example training script](https://github.com/NVIDIA/DeepLearningExamples/blob/63cbbdc2588f7925a4e5cc30bc6e0cb51d9c166a/DGLPyTorch/DrugDiscovery/SE3Transformer/scripts/train.sh) is rune with flags ` --num_degrees 1` and `--low_memory` the code crashes with the following error message:
```
Traceback (most recent call last):
  File "/home/aosokin/anaconda3/envs/se3-transformer-fast/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aosokin/anaconda3/envs/se3-transformer-fast/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aosokin/projects/equivariance/SE3Transformer/se3_transformer/runtime/training.py", line 243, in <module>
    train(model,
  File "/home/aosokin/projects/equivariance/SE3Transformer/se3_transformer/runtime/training.py", line 151, in train
    loss = train_epoch(model, train_dataloader, loss_fn, epoch_idx, grad_scaler, optimizer, local_rank, callbacks,
  File "/home/aosokin/projects/equivariance/SE3Transformer/se3_transformer/runtime/training.py", line 94, in train_epoch
    pred = model(*inputs)
  File "/home/aosokin/anaconda3/envs/se3-transformer-fast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aosokin/projects/equivariance/SE3Transformer/se3_transformer/model/transformer.py", line 212, in forward
    feats = self.transformer(graph, node_feats, edge_feats, basis).squeeze(-1)
  File "/home/aosokin/anaconda3/envs/se3-transformer-fast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aosokin/projects/equivariance/SE3Transformer/se3_transformer/model/transformer.py", line 152, in forward
    node_feats = self.graph_modules(node_feats, edge_feats, graph=graph, basis=basis)
  File "/home/aosokin/anaconda3/envs/se3-transformer-fast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aosokin/projects/equivariance/SE3Transformer/se3_transformer/model/transformer.py", line 46, in forward
    input = module(input, *args, **kwargs)
  File "/home/aosokin/anaconda3/envs/se3-transformer-fast/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aosokin/projects/equivariance/SE3Transformer/se3_transformer/model/layers/convolution.py", line 305, in forward
    self.conv, in_features_fused, invariant_edge_feats, basis['fully_fused']
KeyError: 'fully_fused'
```
This happens because the value `self.fuse_level` is not passed to one of the convolution layers here:
https://github.com/NVIDIA/DeepLearningExamples/blob/63cbbdc2588f7925a4e5cc30bc6e0cb51d9c166a/DGLPyTorch/DrugDiscovery/SE3Transformer/se3_transformer/model/transformer.py#L125-L131

Can be fixed by adding argument ` fuse_level=self.fuse_level` like in this line: https://github.com/NVIDIA/DeepLearningExamples/blob/63cbbdc2588f7925a4e5cc30bc6e0cb51d9c166a/DGLPyTorch/DrugDiscovery/SE3Transformer/se3_transformer/model/transformer.py#L119

**Comment by milesial** [comment]
Hi, thanks for catching this and for the detailed bug report! Expect a fix this week.

**Comment by milesial** [comment]
Fixed in https://github.com/NVIDIA/DeepLearningExamples/commit/f4b9bdfd2f3bc4a096f01d17526ff8e7aa9121f2

**Comment by aosokin** [comment]
Thanks a lot! And thanks for the great code!
