### ISSUE TITLE
[BERT/PyTorch] Getting Attribute error in Step 12 of building docker for BERT pre-training

### ISSUE THREAD

**Issue by l024258** [NVIDIA/DeepLearningExamples#1249]
Related to **BERT/PyTorch(s)** 

**Describe the bug**
Getting this error ```AttributeError: module 'numpy' has no attribute 'int'```  while building the docker for ```Step 12/13 : RUN python -m nltk.downloader punkt```

```
Step 12/13 : RUN python -m nltk.downloader punkt
 ---> Running in 7b03746187fc
/opt/conda/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.1)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/conda/lib/python3.8/site-packages/nltk/__init__.py", line 146, in <module>
    from nltk.chunk import *
  File "/opt/conda/lib/python3.8/site-packages/nltk/chunk/__init__.py", line 155, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/opt/conda/lib/python3.8/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.chunk.util import ChunkScore
  File "/opt/conda/lib/python3.8/site-packages/nltk/chunk/util.py", line 12, in <module>
    from nltk.tag.mapping import map_tag
  File "/opt/conda/lib/python3.8/site-packages/nltk/tag/__init__.py", line 70, in <module>
    from nltk.tag.sequential import (
  File "/opt/conda/lib/python3.8/site-packages/nltk/tag/sequential.py", line 26, in <module>
    from nltk.classify import NaiveBayesClassifier
  File "/opt/conda/lib/python3.8/site-packages/nltk/classify/__init__.py", line 97, in <module>
    from nltk.classify.scikitlearn import SklearnClassifier
  File "/opt/conda/lib/python3.8/site-packages/nltk/classify/scikitlearn.py", line 38, in <module>
    from sklearn.feature_extraction import DictVectorizer
  File "/opt/conda/lib/python3.8/site-packages/sklearn/feature_extraction/__init__.py", line 9, in <module>
    from .image import img_to_graph, grid_to_graph
  File "/opt/conda/lib/python3.8/site-packages/sklearn/feature_extraction/image.py", line 172, in <module>
    dtype=np.int):
  File "/opt/conda/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
The command '/bin/sh -c python -m nltk.downloader punkt' returned a non-zero code: 1
```

**To Reproduce**
1. bash scripts/docker/build.sh

**Environment**
Please provide at least:
* Container version: nvcr.io/nvidia/pytorch:21.11-py3
* GPUs in the system: Tesla V100 16 GB (AWS ml.p3.2xlarge)
* CUDA driver version: 510.47.03

**Comment by l024258** [comment]
Update the docker file with following line,

```
RUN pip install --no-cache-dir \
 numpy==1.22.0 ipython==7.23.1 tqdm boto3 requests six ipdb h5py nltk progressbar onnxruntime tokenizers>=0.7\
 git+https://github.com/NVIDIA/dllogger wget
```
