### ISSUE TITLE
[tspp] Unable to load apex modules after successful install

### ISSUE THREAD

**Issue by DaveBGld** [NVIDIA/DeepLearningExamples#1285]
Related to **Model/Framework(s)** 
*DeepLearningExamples-master/Tools/PyTorch/TimeSeriesPredictionPlatform*

**Describe the bug**
I need to use tspp for a research project, similar to the kaggle: [JPX Tokyo Stock Prediction with NVIDIA-TSPP](https://www.kaggle.com/code/anmolgupta11090/jpx-tokyo-stock-prediction-with-nvidia-tspp).

I proceeded to download all materials and ran the notebook all the way to the **Lunch Training** section, in cell:

```
print("==========TFT===========")
launch_training("tft", tft_cfg, tft_outdir)
base_cfg = tft_cfg
base_outdir = tft_outdir
base_name = "tft"
# print("==========NBEATS===========")
# launch_training("nbeats", nbeats_cfg, nbeats_outdir)
# base_cfg = nbeats_cfg
# base_outdir = nbeats_outdir
# base_name = "nbeats"
# print("==========XGB===========")
# launch_training("xgboost", xgb_cfg, xgb_outdir)
# base_cfg = xgb_cfg
# base_outdir = xgb_outdir
# base_name = "xgboost"
```
Produces error : **ModuleNotFoundError: No module named 'apex.normalization'**

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> File ~/miniconda3/envs/tspp/lib/python3.9/site-packages/hydra/_internal/utils.py:585, in _locate(path)
>     584 try:
> --> 585     import_module(mod)
>     586 except Exception as e:
> 
> File ~/miniconda3/envs/tspp/lib/python3.9/importlib/__init__.py:127, in import_module(name, package)
>     126         level += 1
> --> 127 return _bootstrap._gcd_import(name[level:], package, level)
> 
> File <frozen importlib._bootstrap>:1030, in _gcd_import(name, package, level)
> 
> File <frozen importlib._bootstrap>:1007, in _find_and_load(name, import_)
> 
> File <frozen importlib._bootstrap>:986, in _find_and_load_unlocked(name, import_)
> 
> File <frozen importlib._bootstrap>:680, in _load_unlocked(spec)
> 
> File <frozen importlib._bootstrap_external>:850, in exec_module(self, module)
> 
> File <frozen importlib._bootstrap>:228, in _call_with_frames_removed(f, *args, **kwds)
> 
> File /mnt/DATA/TSPP/Kaggle/nvidia_tspp_code/models/tft_pyt/modeling.py:25
>      24 else:
> ---> 25     from apex.normalization.fused_layer_norm import FusedLayerNorm as LayerNorm
>      27 class MaybeLayerNorm(nn.Module):
> 
> ModuleNotFoundError: No module named 'apex.normalization'
> 
> The above exception was the direct cause of the following exception:
> 
> ImportError                               Traceback (most recent call last)
> Cell In[46], line 2
>       1 print("==========TFT===========")
> ----> 2 launch_training("tft", tft_cfg, tft_outdir)
>       3 base_cfg = tft_cfg
>       4 base_outdir = tft_outdir
> 
> Cell In[22], line 7, in launch_training(model_name, cfg, output_workdir)
>       5 set_seed(cfg.get("seed", None))
>       6 train, valid, test = hydra.utils.call(cfg.dataset)
> ----> 7 model = hydra.utils.instantiate(cfg.model)
>       8 if model_name == "xgboost":
>       9     if cfg.trainer.get("criterion", None):
> 
> File ~/miniconda3/envs/tspp/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py:180, in instantiate(config, *args, **kwargs)
>     177     _recursive_ = config.pop(_Keys.RECURSIVE, True)
>     178     _convert_ = config.pop(_Keys.CONVERT, ConvertMode.NONE)
> --> 180     return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
>     181 else:
>     182     raise InstantiationException(
>     183         "Top level config has to be OmegaConf DictConfig, plain dict, or a Structured Config class or instance"
>     184     )
> 
> File ~/miniconda3/envs/tspp/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py:240, in instantiate_node(node, convert, recursive, *args)
>     238 exclude_keys = set({"_target_", "_convert_", "_recursive_"})
>     239 if _is_target(node):
> --> 240     _target_ = _resolve_target(node.get(_Keys.TARGET))
>     241     kwargs = {}
>     242     for key, value in node.items():
> 
> File ~/miniconda3/envs/tspp/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py:104, in _resolve_target(target)
>     102 """Resolve target string, type or callable into type or callable."""
>     103 if isinstance(target, str):
> --> 104     return _locate(target)
>     105 if isinstance(target, type):
>     106     return target
> 
> File ~/miniconda3/envs/tspp/lib/python3.9/site-packages/hydra/_internal/utils.py:587, in _locate(path)
>     585             import_module(mod)
>     586         except Exception as e:
> --> 587             raise ImportError(
>     588                 f"Encountered error: `{e}` when loading module '{path}'"
>     589             ) from e
>     590     obj = getattr(obj, part)
>     591 if isinstance(obj, type):
> 
> ImportError: Encountered error: `No module named 'apex.normalization'` when loading module 'models.tft_pyt.modeling.TemporalFusionTransformer'

This is with the original values of the notebook and default configuration (amp = false) which I understand **should not require apex**. 

I did install apex from source using default values and[ opened an issue at their repo](https://github.com/NVIDIA/apex/issues/1639): 

**Environment**
> PyTorch version: 1.13.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

> OS: Ubuntu 20.04.6 LTS (x86_64)
> GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> Clang version: Could not collect
> CMake version: version 3.16.3
> Libc version: glibc-2.31

> Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
> Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.31
> Is CUDA available: True
> CUDA runtime version: 11.6.124
> CUDA_MODULE_LOADING set to: LAZY
> GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
> Nvidia driver version: 510.47.03
> cuDNN version: Probably one of the following:
> /usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
> /usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
> /usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
> /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
> /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
> /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
> /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> Is XNNPACK available: True

> Versions of relevant libraries:
> [pip3] numpy==1.21.6
> [pip3] torch==1.13.1+cu116
> [pip3] torchaudio==0.13.1+cu116
> [pip3] torchvision==0.14.1+cu116
> [conda] blas                      1.0                         mkl  
> [conda] mkl                       2021.4.0           h06a4308_640  
> [conda] mkl-service               2.4.0            py39h7f8727e_0  
> [conda] mkl_fft                   1.3.1            py39hd3c417c_0  
> [conda] mkl_random                1.2.2            py39h51133e4_0  
> [conda] numpy                     1.21.6                   pypi_0    pypi
> [conda] torch                     1.13.1+cu116             pypi_0    pypi
> [conda] torchaudio                0.13.1+cu116             pypi_0    pypi
> [conda] torchvision               0.14.1+cu116             pypi_0    pypi
>

**Comment by IzzyPutterman** [comment]
Hey,

Happy to hear that you are using the TSPP!  We recommend using the NGC docker images which come with Apex installed.  You can find how to build the TSPP image in the quick start guide: https://github.com/NVIDIA/DeepLearningExamples/tree/master/Tools/PyTorch/TimeSeriesPredictionPlatform#quick-start-guide.  

If you are unable to use the Docker image, this error seems to come from instantiating the TFT which uses the APEX FusedLayerNorm.  Last week, we updated the TFT and effectively dropped all dependence on the deprecated APEX modules (including FusedLayerNorm).  If you update the tft_pyt directory to the files here: https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Forecasting/TFT, it should work.  As we now use some scripting to make use of the NvFuser, you will need to update the config files here: https://github.com/NVIDIA/DeepLearningExamples/blob/master/Tools/PyTorch/TimeSeriesPredictionPlatform/conf/model/tft.yaml#L21 and for the `conf/model_dataset/tft_{electricity/traffic}.yaml` to make the attn_dropout input a float instead of an int.  This can be done by simply swapping the `0` for a `0.0`.  

As an alternative solution, one can modify this line: https://github.com/NVIDIA/DeepLearningExamples/blob/master/Tools/PyTorch/TimeSeriesPredictionPlatform/models/tft_pyt/modeling.py#L25, to be `from torch.nn import LayerNorm`.  FusedLayerNorm gives us a performance increase, but is not necessary to run.

Let us know if these work arounds are useful.

**Comment by DaveBGld** [comment]
Thanks @IzzyPutterman !! I got homework. I'll update as of progress

**Comment by IzzyPutterman** [comment]
I am not exactly sure what the C header issue is, but the recommended way of running the TSPP locally is to follow the Quick Start Guide: https://github.com/NVIDIA/DeepLearningExamples/tree/master/Tools/PyTorch/TimeSeriesPredictionPlatform#quick-start-guide.  The Kaggle page was setup to follow the inbuilt kaggle environment, which may be difficult to replicate.  

Would you be able to use docker for the project?  What information do you need from the JPX competition?  I believe that all the scripts on the competition should run inside the provided docker image.

**Comment by DaveBGld** [comment]
@IzzyPutterman Thanks!

My intention is to see a tspp working example end to end so I can understand the mechanics of adding features, changing timeframes, etc... such that I can create my own datasets and experiment.

Seeing the code on a kaggle notebook is very helpful to me to understand, and therefore, I will work on the notebook to prepare the data, and train on the tspp docker. Thanks for the advise.

On a sideline, I see in your data preprocessing that there is a column called Target, that exists from the initial `train_sp_file = "train_files/stock_prices.csv"` and is not manipulated but persists to the file `filtered_stock_prices.csv`.  I am curious to know what is this column, as it seems anyhow that is not taken into account since its absent from the `jpx.yaml` config file...???

Many thanks,

**Comment by Pyroluk** [comment]
Hi,
I have a similar problem. Using the latest TFT version in TSPP (Docker) and enabling AMP, I get the following error:
```
ValueError: Error instantiating 'training.trainer.CTLTrainer' : Attempted to use an uninitialized parameter in <method 'type' of 'torch._C._TensorBase' objects>.
This error happens when you are using a `LazyModule` or explicitly manipulating `torch.nn.parameter.UninitializedParameter` objects.
When using LazyModules Call `forward` with a dummy batch to initialize the parameters before calling torch functions
```
Crash happens on line 105 in /training/trainer.py :
https://github.com/NVIDIA/DeepLearningExamples/blob/master/Tools/PyTorch/TimeSeriesPredictionPlatform/training/trainer.py#L105

I guess this is caused by the new LazyEmbedding?
That also crashes [Weights & Biases](https://wandb.ai/site) `wandb.watch(model, log_freq=100)` call on an untrained fresh model.

**Comment by Pyroluk** [comment]
Hi,
got it kind of working with the dummy_batch code and the TFT_SCRIPTING=False flag. For other readers here, the self.train_dataloader init code needs to be moved above that code in order for self.train_dataloader to be defined.

Not sure if it is just my use case, but I get "Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to XXX" messages and no actual training steps with these modifications.

**Comment by IzzyPutterman** [comment]
Does your code run when using the old version of the TFT, I think currently present in the models/ directory?
Can you train electricity  with `TFT_SCRIPTING=false python launch_training.py model=tft dataset=electricity trainer/criterion=quantile trainer.config.num_epochs=1` and get an MAE of ~42-46?

**Comment by Pyroluk** [comment]
Had to reduce the batch size for a quick run on my local 8GB GPU:
`TFT_SCRIPTING=false`
`model=tft dataset=electricity trainer/criterion=quantile trainer.config.num_epochs=1 trainer.config.amp=true trainer.config.batch_size=768`

Results:
`MAE : 0.2200114130973816  RMSE : 0.3554209768772125  SMAPE : 38.33830654621124  ND : 0.23568664491176605`

Any idea what is going on?

**Comment by IzzyPutterman** [comment]
I am honestly not sure what the issue above is.  Would you be able to re-preprocess the data and run again?  What do you get if you use the old TFT code?

**Comment by Pyroluk** [comment]
Fresh repro pull and docker build solved the problem.
`TFT_SCRIPTING=false python launch_training.py model=tft dataset=electricity trainer/criterion=quantile trainer.config.num_epochs=1 trainer.config.amp=true trainer.config.batch_size=768`
Results:
`MAE : 45.368255561589564  RMSE : 368.65816141232375  SMAPE : 9.376580496996748  ND : 0.05971924853083785`

Thank you for your help.
Can you roughly predict the time of release for the next TSPP version?

**Comment by IzzyPutterman** [comment]
Awesome, glad that strangeness is fixed.  I cannot give a timeline on release, but I will update this post when it is out.

**Comment by DaveBGld** [comment]
Hi @IzzyPutterman !!  Thanks for the help... 

I created the docker, and training the electricity dataset works fine with 
`python launch_training.py dataset=electricity model=tft trainer/criterion=quantile`

Back to the jpx, as I planned, executed all the preparations on the notebook, and put the data in a directory that maps to `/workspace/datasets/jpx/`

Also updated the jpx.yaml configuration file from the jpx notebook to have 
```
  source_path: /workspace/datasets/jpx/filtered_stock_prices.csv
  dest_path: /workspace/datasets/jpx/
```

[complete jpx.yaml](https://github.com/NVIDIA/DeepLearningExamples/files/11278308/jpx.yaml.txt)

Put the jpx.yaml file in `/workspace/conf/dataset`

then run 
`python launch_training.py dataset=electricity model=tft trainer/criterion=quantile`

Which results in error **Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks'**
Complete log:

> 	

> root@AI01:/workspace# python launch_training.py dataset=jpx model=tft trainer/criterion=quantile
> Using backend: pytorch
> Error executing job with overrides: ['dataset=jpx', 'model=tft', 'trainer/criterion=quantile']
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
>     return _target_(*args, **kwargs)
>   File "/workspace/evaluators/evaluator.py", line 107, in __init__
>     super().__init__(config)
>   File "/workspace/evaluators/evaluator.py", line 34, in __init__
>     preprocessor_state = pickle.load(open(config.preprocessor_state_path, "rb"))
> AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/opt/conda/lib/python3.8/site-packages/pandas/core/internals/blocks.py'>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "launch_training.py", line 36, in main
>     evaluator = hydra.utils.instantiate(config.evaluator, test_data=test)
>   File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
>     return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
>   File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
>     return _call_target(_target_, *args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 64, in _call_target
>     raise type(e)(
>   File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
>     return _target_(*args, **kwargs)
>   File "/workspace/evaluators/evaluator.py", line 107, in __init__
>     super().__init__(config)
>   File "/workspace/evaluators/evaluator.py", line 34, in __init__
>     preprocessor_state = pickle.load(open(config.preprocessor_state_path, "rb"))
> AttributeError: Error instantiating 'evaluators.evaluator.CTLMetricEvaluator' : Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/opt/conda/lib/python3.8/site-packages/pandas/core/internals/blocks.py'>
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> root@AI01:/workspace# 
> 
>

**Comment by IzzyPutterman** [comment]
@DaveBGld In what environment was the JPX data preprocessed?  Did you copy the preprocessed data from the kaggle environment as well, or did you preprocess in the Docker?

**Comment by DaveBGld** [comment]
@IzzyPutterman Thanks!!! 

I completed a training session for the jpx by preprocessing within the tspp docker...

Now, my current walkabout is to experience the complete path, step by step, from data, through training, to edge inference using tensorRT.

So, after training, I reloaded the docker with 

`docker run -it --rm --gpus all --ipc=host --network=host -v /mnt/DATA/TSPP/DATA/:/workspace/datasets/  -v /mnt/DATA/TSPP/DATA/multirun/:/workspace/multirun/ -v /mnt/DATA/TSPP/DATA/outputs:/workspace/outputs -v $(pwd):$(pwd) -v /var/run/docker.sock:/var/run/docker.sock tspp`

and run an export with:

`python launch_triton_configure.py deployment/export=onnx deployment/convert=trt checkpoint=/workspace/outputs/2023-04-20/08-01-59`

This runs for about 6 minutes and produces an error: 

> 
>   File "triton/check_accuracy.py", line 152, in <module>
>     main()
>   File "triton/check_accuracy.py", line 141, in main
>     assert all([i < 1e-3 for i in e1]), **"Error between native and export is {}, limit is 1e-3".format(e1)**
> 

AND

> TypeError: __init__() missing 1 required positional argument: 'cmd'


[Full error log Here](https://github.com/NVIDIA/DeepLearningExamples/files/11284619/tspp.trt.export.error.log.txt)

**Comment by DaveBGld** [comment]
@IzzyPutterman  Thank you!

I have completed training and export to tensorRT after commenting the line you indicated...

My next step is to create an inference engine in C++ with thesorRT (I do that often with video frames), and I have two questions:

a) **Where is the tensorRT** engine file after export?

and

b) Assuming I have 10 rows of data foe the same stock, what is the **preprocessing needed,** and **what shape will the input and output tensors have?**

Many Thanks!!

**Comment by IzzyPutterman** [comment]
The tensortRT plan (engine file) should be present in the `checkpoint=/workspace/outputs/2023-04-20/08-01-59` directory under deployment/navigator_workspace/converted/.

Is this data preprocessed yet?

**Comment by DaveBGld** [comment]
@IzzyPutterman  Thanks! 

From the JPX Notebook I count 24 features, but polygraphy reports  only 5?

Also, if I get an instance of current data to feed to the model, how can I run scalers to normalize the features, if there is just one data instance?

> features = [
>     {'name': 'id', 'feature_type': 'ID', 'feature_embed_type': 'CATEGORICAL', 'cardinality': time_series_count+1},
>     {'name': 'Timestep', 'feature_type': 'TIME', 'feature_embed_type': 'CONTINUOUS'},
>     {'name': 'Weight', 'feature_type': 'WEIGHT', 'feature_embed_type': 'CONTINUOUS'},
>     {'name': 'AdjustedClose', 'feature_type': 'TARGET', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'DayOfWeek', 'feature_type': 'KNOWN', 'feature_embed_type': 'CATEGORICAL', 'cardinality': 6},
>     {'name': 'Timestep', 'feature_type': 'KNOWN', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'Month', 'feature_type': 'KNOWN', 'feature_embed_type': 'CATEGORICAL', 'cardinality': 13},
>     {'name': 'Day', 'feature_type': 'KNOWN', 'feature_embed_type': 'CATEGORICAL', 'cardinality': 32},
>     {'name': 'AdjustedOpen', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'AdjustedHigh', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'AdjustedLow', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'Volume', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'id', 'feature_type': 'STATIC', 'feature_embed_type': 'CATEGORICAL', 'cardinality': time_series_count+1},
>     {'name': 'IsMonday', 'feature_type': 'KNOWN', 'feature_embed_type': 'CATEGORICAL', 'cardinality': 3},
>     {'name': 'Close_1week_mean', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'Close_1week_std', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'Close_1week_min', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'Close_1week_max', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'Close_4weeks_mean', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'Close_4weeks_std', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'Close_4weeks_min', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'Close_4weeks_max', 'feature_type': 'OBSERVED', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'DayOfYear', 'feature_type': 'KNOWN', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
>     {'name': 'Year', 'feature_type': 'KNOWN', 'feature_embed_type': 'CONTINUOUS', 'scaler': {'_target_': 'sklearn.preprocessing.StandardScaler'}},
> ]

After creating the jpx.yaml conf file fron the Kaggle notebook, I run in the tspp docker:

docker run -it --rm --gpus all --ipc=host --network=host -v /mnt/DATA/TSPP/DATA/:/workspace/datasets/  -v /mnt/DATA/TSPP/DATA/multirun/:/workspace/multirun/ -v /mnt/DATA/TSPP/DATA/outputs:/workspace/outputs -v $(pwd):$(pwd) -v /var/run/docker.sock:/var/run/docker.sock tspp
```

cp /workspace/datasets/jpx/jpx.yaml /workspace/conf/dataset
python launch_preproc.py dataset=jpx
python launch_training.py dataset=jpx model=tft trainer/criterion=quantile
python launch_triton_configure.py deployment/export=onnx deployment/convert=trt checkpoint=/workspace/outputs/2023-04-23/13-08-18
cd /workspace/outputs/2023-04-23/13-08-18/deployment/navigator_workspace/converted
polygraphy inspect model exported_model-polygraphyonnx2trt_fp32_mh.plan

```

> polygraphy inspect model exported_model-polygraphyonnx2trt_fp32_mh.plan
> [I] Loading bytes from /workspace/outputs/2023-04-23/13-08-18/deployment/navigator_workspace/converted/exported_model-polygraphyonnx2trt_fp32_mh.plan
> [I] ==== TensorRT Engine ====
>     Name: Unnamed Network 0 | Explicit Batch Engine
>     
>     ---- 5 Engine Input(s) ----
>     {s_cat__0 [dtype=int32, shape=(-1, 12, 1)],
>      k_cat__2 [dtype=int32, shape=(-1, 12, 4)],
>      k_cont__3 [dtype=float32, shape=(-1, 12, 3)],
>      o_cont__5 [dtype=float32, shape=(-1, 12, 12)],
>      target__6 [dtype=float32, shape=(-1, 12, 1)]}
>     
>     ---- 1 Engine Output(s) ----
>     {target__0 [dtype=float32, shape=(-1, 2, 3)]}
>     
>     ---- Memory ----
>     Device Memory: 108103168 bytes
>     
>     ---- 1 Profile(s) (6 Binding(s) Each) ----
>     - Profile: 0
>         Binding Index: 0 (Input)  [Name: s_cat__0]  | Shapes: min=(1, 12, 1), opt=(64, 12, 1), max=(64, 12, 1)
>         Binding Index: 1 (Input)  [Name: k_cat__2]  | Shapes: min=(1, 12, 4), opt=(64, 12, 4), max=(64, 12, 4)
>         Binding Index: 2 (Input)  [Name: k_cont__3] | Shapes: min=(1, 12, 3), opt=(64, 12, 3), max=(64, 12, 3)
>         Binding Index: 3 (Input)  [Name: o_cont__5] | Shapes: min=(1, 12, 12), opt=(64, 12, 12), max=(64, 12, 12)
>         Binding Index: 4 (Input)  [Name: target__6] | Shapes: min=(1, 12, 1), opt=(64, 12, 1), max=(64, 12, 1)
>         Binding Index: 5 (Output) [Name: target__0] | Shape: (-1, 2, 3)
>     
>     ---- 2 Layer(s) ----

**Comment by IzzyPutterman** [comment]
Hey, 

We reorganize the features and group them based on the "feature_type" and "feature_embed_type".  Each input is of the shape (batch, example_length, features).  From the Engine profile:
s_cat: Last dimension is 1, so we have 1 static categorical (ID)
k_cat: Last dimension is 4, so we have 4 known categoricals
k_cont: Last dimension is 3, so we have 3 known continuous, and so on.

For the preprocessing, we have a flag that can be used for the inference.  I have an old post with some details: https://github.com/NVIDIA/DeepLearningExamples/issues/1199#issuecomment-1239808458, the flag can be used on native and triton inference.  Let me know about any questions.

**Comment by DaveBGld** [comment]
@IzzyPutterman  Thanks. That was quick and enlightening...

1. What is the order within each _feature_type_? appearance in the features declaration? Also, there are I think **18 continuous and 6 categoricals** in the features definition of the Kaggle notebook... **Which are dropped?** 

2. I read the 1199 comment but I get two issues with that... On the one hand, I intend to run under tensorRT so I don't have access to the flag... On the other hand, gives me more doubts. Isn't it enough to provide a set of real feature values for **encoder_length** time slots and the model will return (example_length - encoder_length) time slots? But those I'll need to standardize, so it looks like I'll have to modify the preprocess to output the mean and std deviation for each feature every time I train with new data to use for standardization at inference time?

3. The output tensor has dimension 2, I assume 2 time slots in the future for the target feature, but also dimension 3? Is it predicting the values of 3 features for the next two time slots? Which features? 

4. One last observation:  the avg loss is 0.179 from step 24375 in epoch 2 all the way to the end at step 159350 epoch 14 with some variations up and down... It's not converging? How can I improve the convergence?

Many many thanks for your quick and direct support. I appreciate!!!

D

**Comment by IzzyPutterman** [comment]
Hey,

1.  From my calculations, we have 1 static cat, 4 known cats, 3 known conts, 12 observed conts, and 1 target cont.  I believe the first ID has the dtype ID and is not used (which is why we list the ID also as a STATIC separately.  I believe Weight is included but timestep (with dtype=Time) is dropped, some of the code is present here in group_ids: https://github.com/NVIDIA/DeepLearningExamples/blob/1e103522fef1066bf1ae94d5b9c8b2cee72a5d92/Tools/PyTorch/TimeSeriesPredictionPlatform/data/data_utils.py#L113.  I will need to confirm this with the team.
2.  For the feature preproc, we save the standard scaler for each vector/ID.  This scaler contains the mean and std of the feature in the training set.  If you recalculate the mean/std for each test example, you are changing the distribution the model was trained on, which can lead to poor results.  As a side note, our NVIDIA Triton Inference server supports the TensorRT backend, and you can directly deploy/query the TensorRT engine from the TSPP.  Does that fit your use case? 
3.  For this one, the output is of shape (batch, forecast_length, quantiles).  So as you state, the forecast_length is 2, and you are using the TFT model, with I assume the default prediction head.  This means it outputs 3 quantiles, [0.1, 0.5, 0.9], so the last dimension are the 3 quantile predictions.  This config handles the default quantile: https://github.com/NVIDIA/DeepLearningExamples/blob/master/Tools/PyTorch/TimeSeriesPredictionPlatform/conf/trainer/criterion/overrides/quantile_overrides.yaml.  
4.  This is always a little tricky.  However is the avg loss is staying pretty constant, I would say it has converged to its best value given the parameters/features.  I would attribute the increase in validation loss to the model overfitting to the training data.  In order to improve the metrics, you can experiment with the hyper-parameter sweeps, a guide is here: https://github.com/NVIDIA/DeepLearningExamples/tree/master/Tools/PyTorch/TimeSeriesPredictionPlatform#hyperparameter-search
