### ISSUE TITLE
ValueError: Could not find container with id=docker-7ec

### ISSUE THREAD

**Issue by pengpengzzz** [NVIDIA/DeepLearningExamples#1288]
when i tryed deplay the bert on triton inference server Step by step deployment [process,](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/triton/large/README.md#convert-model),I got the following error:
`2023-04-16 14:50:49 - DEBUG - model_navigator.log: initialized logger verbose=True
2023-04-16 14:50:49 - DEBUG - convert: Running 'model-navigator convert' with config_path: None
Traceback (most recent call last):
  File "/opt/conda/bin/model-navigator", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/model_navigator/cli/main.py", line 49, in main
    cli(max_content_width=160)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/model_navigator/cli/convert_model.py", line 408, in convert_cmd
    run_command_validators(
  File "/opt/conda/lib/python3.8/site-packages/model_navigator/validators.py", line 72, in run_command_validators
    environment_state = _get_env_state(configuration)
  File "/opt/conda/lib/python3.8/site-packages/model_navigator/validators.py", line 89, in _get_env_state
    environment_state = get_environment_state()
  File "/opt/conda/lib/python3.8/site-packages/model_navigator/utils/env.py", line 41, in get_environment_state
    container = DockerContainer(docker_container_id)
  File "/opt/conda/lib/python3.8/site-packages/model_navigator/utils/docker.py", line 44, in __init__
    raise ValueError(f"Could not find container with id={container_id}")
ValueError: Could not find container with id=docker-7ec
`

**Comment by pengpengzzz** [comment]
The error comes from the Convert Model step
