### ISSUE TITLE
fastpitch+hifigan inference ran into error

### ISSUE THREAD

**Issue by pragyachaturvedi99** [NVIDIA/DeepLearningExamples#1312]
I tried inferencing using waveglow and it worked just fine but soon as I changed to hifigan it threw the following error
Traceback (most recent call last):
  File "inference.py", line 571, in <module>
    main()
  File "inference.py", line 397, in main
    raise ValueError(f'Invalid options {unk_args}')
ValueError: Invalid options ['256', '--wn-channels']

**Comment by itamar-dw** [comment]
The error is self-explanatory: HiFiGAN model does not have a parameter called `wn-channels`. 
Check your inference code.
