### ISSUE TITLE
[DLRM/TensorFlow2] Can't Run Training On 1 GPU With Generated Synthetic Data

### ISSUE THREAD

**Issue by psharpe99** [NVIDIA/DeepLearningExamples#1316]
Related to **DLRM/TensorFlow2** 

**Describe the bug**
As per the README, I created synthetic CSV data, transcoded it, and then tried to train the model with it.
The _loss_ variable is not created inside the epoch step training loop, and python aborts from this.
Extra debug shows that the len(train_pipeline) is 0, so there are no epoch steps at main.py:316
The _train_pipeline_ is created at main.py:254, but it's unclear why this would be effectively zero sized.

**To Reproduce**

root@biber:/home/psharpe/DeepLearningExamples-master/TensorFlow2/Recommendation/DLRM# export DATASET_PARENT_DIRECTORY=`pwd`

root@biber:/home/psharpe/DeepLearningExamples-master/TensorFlow2/Recommendation/DLRM# echo $DATASET_PARENT_DIRECTORY
/home/psharpe/DeepLearningExamples-master/TensorFlow2/Recommendation/DLRM

root@biber:/home/psharpe/DeepLearningExamples-master/TensorFlow2/Recommendation/DLRM# docker run --cap-add SYS_NICE --runtime=nvidia -it --rm --ipc=host  -v ${DATASET_PARENT_DIRECTORY}/data:/data nvidia_dlrm_tf bash

root@7cf568793223:/dlrm# python gen_csv.py --feature_spec_in tests/transcoding/small_csv.yaml

root@7cf568793223:/dlrm# mkdir /data/conversion_output

root@7cf568793223:/dlrm# cp tests/transcoding/small_csv.yaml /data/feature_spec.yaml

root@7cf568793223:/dlrm# python transcode.py --input /data --output /data/converted

root@7cf568793223:/dlrm# horovodrun -np 1 -H localhost:1 --mpi-args=--oversubscribe numactl --interleave=all -- python -u main.py --dataset_path /data/converted --amp --xla
2023-06-26 10:34:53.452961: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[1,0]<stderr>:2023-06-26 10:34:55.658858: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[1,0]<stdout>:DLL 2023-06-26 10:34:57.657737 - PARAMETER logtostderr : False  alsologtostderr : False  log_dir :   v : 0  verbosity : 0  logger_levels : {}  stderrthreshold : fatal  showprefixforinfo : True  run_with_pdb : False  pdb_post_mortem : False  pdb : False  run_with_profiling : False  profile_file : None  use_cprofile_for_profiling : True  only_check_args : False  op_conversion_fallback_to_while_loop : True  runtime_oom_exit : True  hbm_oom_exit : True  test_srcdir :   test_tmpdir : /tmp/absl_testing  test_random_seed : 301  test_randomize_ordering_seed :   xml_output_file :   mode : train  learning_rate : 24.0  batch_size : 65536  run_eagerly : False  dummy_model : False  top_mlp_dims : [1024, 1024, 512, 256, 1]  bottom_mlp_dims : [512, 256, 128]  optimizer : sgd  save_checkpoint_path : None  restore_checkpoint_path : None  saved_model_output_path : None  save_input_signature : False  saved_model_input_path : None  cpu : False  amp : True  fp16 : False  xla : True  loss_scale : 1024  auc_thresholds : 8000  epochs : 1  max_steps : -1  embedding_trainable : True  dot_interaction : custom_cuda  embedding_dim : 128  evals_per_epoch : 1  print_freq : 100.0  warmup_steps : 8000  decay_start_step : 48000  decay_steps : 24000  profiler_start_step : None  profiled_rank : 1  inter_op_parallelism : None  intra_op_parallelism : None  dist_strategy : memory_balanced  use_merlin_de_embeddings : False  column_slice_threshold : 10000000000  log_path : dlrm_tf_log.json  dataset_path : /data/converted  feature_spec : feature_spec.yaml  dataset_type : tf_raw  synthetic_dataset_use_feature_spec : False  synthetic_dataset_train_batches : 64008  synthetic_dataset_valid_batches : 1350  synthetic_dataset_cardinalities : [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]  synthetic_dataset_num_numerical_features : 13  ? : False  help : False  helpshort : False  helpfull : False  helpxml : False 
[1,0]<stdout>:Command line flags:
[1,0]<stdout>:{
[1,0]<stdout>:    "logtostderr": false,
[1,0]<stdout>:    "alsologtostderr": false,
[1,0]<stdout>:    "log_dir": "",
[1,0]<stdout>:    "v": 0,
[1,0]<stdout>:    "verbosity": 0,
[1,0]<stdout>:    "logger_levels": {},
[1,0]<stdout>:    "stderrthreshold": "fatal",
[1,0]<stdout>:    "showprefixforinfo": true,
[1,0]<stdout>:    "run_with_pdb": false,
[1,0]<stdout>:    "pdb_post_mortem": false,
[1,0]<stdout>:    "pdb": false,
[1,0]<stdout>:    "run_with_profiling": false,
[1,0]<stdout>:    "profile_file": null,
[1,0]<stdout>:    "use_cprofile_for_profiling": true,
[1,0]<stdout>:    "only_check_args": false,
[1,0]<stdout>:    "op_conversion_fallback_to_while_loop": true,
[1,0]<stdout>:    "runtime_oom_exit": true,
[1,0]<stdout>:    "hbm_oom_exit": true,
[1,0]<stdout>:    "test_srcdir": "",
[1,0]<stdout>:    "test_tmpdir": "/tmp/absl_testing",
[1,0]<stdout>:    "test_random_seed": 301,
[1,0]<stdout>:    "test_randomize_ordering_seed": "",
[1,0]<stdout>:    "xml_output_file": "",
[1,0]<stdout>:    "mode": "train",
[1,0]<stdout>:    "learning_rate": 24.0,
[1,0]<stdout>:    "batch_size": 65536,
[1,0]<stdout>:    "run_eagerly": false,
[1,0]<stdout>:    "dummy_model": false,
[1,0]<stdout>:    "top_mlp_dims": [
[1,0]<stdout>:        1024,
[1,0]<stdout>:        1024,
[1,0]<stdout>:        512,
[1,0]<stdout>:        256,
[1,0]<stdout>:        1
[1,0]<stdout>:    ],
[1,0]<stdout>:    "bottom_mlp_dims": [
[1,0]<stdout>:        512,
[1,0]<stdout>:        256,
[1,0]<stdout>:        128
[1,0]<stdout>:    ],
[1,0]<stdout>:    "optimizer": "sgd",
[1,0]<stdout>:    "save_checkpoint_path": null,
[1,0]<stdout>:    "restore_checkpoint_path": null,
[1,0]<stdout>:    "saved_model_output_path": null,
[1,0]<stdout>:    "save_input_signature": false,
[1,0]<stdout>:    "saved_model_input_path": null,
[1,0]<stdout>:    "cpu": false,
[1,0]<stdout>:    "amp": true,
[1,0]<stdout>:    "fp16": false,
[1,0]<stdout>:    "xla": true,
[1,0]<stdout>:    "loss_scale": 1024,
[1,0]<stdout>:    "auc_thresholds": 8000,
[1,0]<stdout>:    "epochs": 1,
[1,0]<stdout>:    "max_steps": -1,
[1,0]<stdout>:    "embedding_trainable": true,
[1,0]<stdout>:    "dot_interaction": "custom_cuda",
[1,0]<stdout>:    "embedding_dim": 128,
[1,0]<stdout>:    "evals_per_epoch": 1,
[1,0]<stdout>:    "print_freq": 100.0,
[1,0]<stdout>:    "warmup_steps": 8000,
[1,0]<stdout>:    "decay_start_step": 48000,
[1,0]<stdout>:    "decay_steps": 24000,
[1,0]<stdout>:    "profiler_start_step": null,
[1,0]<stdout>:    "profiled_rank": 1,
[1,0]<stdout>:    "inter_op_parallelism": null,
[1,0]<stdout>:    "intra_op_parallelism": null,
[1,0]<stdout>:    "dist_strategy": "memory_balanced",
[1,0]<stdout>:    "use_merlin_de_embeddings": false,
[1,0]<stdout>:    "column_slice_threshold": 10000000000,
[1,0]<stdout>:    "log_path": "dlrm_tf_log.json",
[1,0]<stdout>:    "dataset_path": "/data/converted",
[1,0]<stdout>:    "feature_spec": "feature_spec.yaml",
[1,0]<stdout>:    "dataset_type": "tf_raw",
[1,0]<stdout>:    "synthetic_dataset_use_feature_spec": false,
[1,0]<stdout>:    "synthetic_dataset_train_batches": 64008,
[1,0]<stdout>:    "synthetic_dataset_valid_batches": 1350,
[1,0]<stdout>:    "synthetic_dataset_cardinalities": [
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000,
[1,0]<stdout>:        1000
[1,0]<stdout>:    ],
[1,0]<stdout>:    "synthetic_dataset_num_numerical_features": 13,
[1,0]<stdout>:    "?": false,
[1,0]<stdout>:    "help": false,
[1,0]<stdout>:    "helpshort": false,
[1,0]<stdout>:    "helpfull": false,
[1,0]<stdout>:    "helpxml": false
[1,0]<stdout>:}
[1,0]<stderr>:INFO:tensorflow:Mixed precision compatibility check (mixed_float16): OK
[1,0]<stderr>:Your GPUs will likely run quickly with dtype policy mixed_float16 as they all have compute capability of at least 7.0
[1,0]<stderr>:I0626 10:34:57.660366 139744096528192 device_compatibility_check.py:123] Mixed precision compatibility check (mixed_float16): OK
[1,0]<stderr>:Your GPUs will likely run quickly with dtype policy mixed_float16 as they all have compute capability of at least 7.0
[1,0]<stderr>:2023-06-26 10:34:57.674412: I tensorflow/core/platform/cpu_feature_guard.cc:194] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
[1,0]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,0]<stderr>:2023-06-26 10:34:58.513959: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 37981 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:31:00.0, compute capability: 8.0
[1,0]<stderr>:2023-06-26 10:34:59.027965: W tensorflow/core/framework/dataset.cc:768] Input of GeneratorDatasetOp::Dataset will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
[1,0]<stdout>:Starting epoch:  0
[1,0]<stdout>:Training run completed, elapsed: 0 [s]
[1,0]<stdout>:Run too short to measure mean training time
[1,0]<stdout>:Run too short to measure mean training time
**[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "main.py", line 364, in <module>
[1,0]<stderr>:    app.run(main)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
[1,0]<stderr>:    _run_main(main, args)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
[1,0]<stderr>:    sys.exit(main(argv))
[1,0]<stderr>:  File "main.py", line 358, in main
[1,0]<stderr>:    'train_loss': loss.numpy().item()
[1,0]<stderr>:UnboundLocalError: local variable 'loss' referenced before assignment**
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[37004,1],0]
  Exit code:    1
--------------------------------------------------------------------------

**Expected behavior**
I expected that the training run would complete successfully, as this was script-generated synthetic data as per the README instructions.

**Environment**

Container version:
root@7cf568793223:/dlrm# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"

root@7cf568793223:/dlrm# python --version
Python 3.8.10

Container devices:
root@7cf568793223:/dlrm# nvidia-smi
Mon Jun 26 10:36:55 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.116.04   Driver Version: 525.116.04   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  Off  | 00000000:31:00.0 Off |                    0 |
| N/A   34C    P0    34W / 250W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:4B:00.0 Off |                    0 |
| N/A   37C    P0    27W / 250W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by tgrel** [comment]
Hi @psharpe99,

We have just released a major update to this example. One of the new features is a redesign of the synthetic dataset functionality. It should fix your issues. You can try it by following the instructions in the [Quick Start Guide](https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow2/Recommendation/DLRM_and_DCNv2/doc/DLRM.md#quick-start-guide).
