### ISSUE TITLE
error running `run_squad.py`,

### ISSUE THREAD

**Issue by Meiyim** [NVIDIA/DeepLearningExamples#191]
hi, i ran into error when playing with `DeepLearningExamples/TensorFlow/LanguageModeling/BERT/run_squad.py`.
the command i use: 
```script
bash scripts/run_squad.sh 8 5e-6 fp32 true 1 384 128 base
```
error message i got:
```script
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "run_squad.py", line 1158, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad.py", line 1034, in main
    estimator.train(input_fn=train_input_fn, hooks=training_hooks, max_steps=num_train_steps)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1154, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "run_squad.py", line 339, in model_fn
    total_loss, learning_rate, num_train_steps, num_warmup_steps, hvd, amp=use_fp16)
TypeError: create_optimizer() got an unexpected keyword argument 'amp'
Traceback (most recent call last):
  File "data/squad/v1.1/evaluate-v1.1.py", line 92, in <module>
    with open(args.prediction_file) as prediction_file:
FileNotFoundError: [Errno 2] No such file or directory: '/results/tf_bert_base_squad_1n_fp32_gbs8_190905123849/predictions.json'
```
seems this line doesn't match the definition of `optimization.create_optimizer`
https://github.com/NVIDIA/DeepLearningExamples/blob/da8acb12889b1c3450f6e353b8a2e4e047fc015f/TensorFlow/LanguageModeling/BERT/run_squad.py#L338
can anybody take a look?

**Comment by swethmandava** [comment]
Fixed in #200 . Sorry for the version mismatch
