### ISSUE TITLE
RuntimeError: expected backend CPU and dtype Float but got backend CUDA and dtype Float

### ISSUE THREAD

**Issue by rakshithvasudev** [NVIDIA/DeepLearningExamples#245]
This is an issue concerning the following repo:
[(https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/Tacotron2)](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/Tacotron2)

I've trained Tacotron2 and Waveglow. I'm trying to infer from the saved checkpoints for both models as follows: 

`python $TTS/inference.py --tacotron2 $TTS/new_ckpts_tt2/checkpoint_Tacotron2_2000 --waveglow $TTS/new_ckpts_waveglow/checkpoint_WaveGlow_2000 -o synthesized/ --include-warmup -i phrases/phrase_1_64.txt --log-file=synthesized/nvlog_fp32.json`

I get the following error : 

```
:::NVLOGv0.2.2 Tacotron2_PyT 1570212612.014624119 (/mnt/isilon/rakvee/models/tt2/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) cpu_info: {"num": 40, "name": "Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz"}
:::NVLOGv0.2.2 Tacotron2_PyT 1570212612.023746252 (/mnt/isilon/rakvee/models/tt2/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) mem_info: {"ram": "376G"}
:::NVLOGv0.2.2 Tacotron2_PyT 1570212612.467813730 (/mnt/isilon/rakvee/models/tt2/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) gpu_info: {"driver_version": "418.67", "num": 4, "name": ["Tesla V100-SXM2-32GB", "Tesla V100-SXM2-32GB", "Tesla V100-SXM2-32GB", "Tesla V100-SXM2-32GB"], "mem": ["32480 MiB", "32480 MiB", "32480 MiB", "32480 MiB"]}
:::NVLOGv0.2.2 Tacotron2_PyT 1570212612.468524694 (/mnt/isilon/rakvee/models/tt2/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) args: {"input": "phrases/phrase_1_64.txt", "output": "synthesized/", "tacotron2": "/home/rakvee/isilon/rakvee/models/tt2/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/new_ckpts_tt2/checkpoint_Tacotron2_2000", "waveglow": "/home/rakvee/isilon/rakvee/models/tt2/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/new_ckpts_waveglow/checkpoint_WaveGlow_2000", "sigma_infer": 0.9, "denoising_strength": 0.01, "sampling_rate": 22050, "amp_run": false, "log_file": "synthesized/nvlog_fp16.json", "include_warmup": true, "stft_hop_length": 256}
Traceback (most recent call last):
  File "/home/rakvee/isilon/rakvee/models/tt2/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/inference.py", line 272, in <module>
    main()
  File "/home/rakvee/isilon/rakvee/models/tt2/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/inference.py", line 250, in main
    audios = denoiser(audios, strength=args.denoising_strength).squeeze(1)
  File "/home/rakvee/isilon/rakvee/installed_apps/conda/envs/torch1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/isilon/rakvee/models/tt2/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/waveglow/denoiser.py", line 64, in forward
    audio_spec_denoised = audio_spec - self.bias_spec * strength
RuntimeError: expected backend CPU and dtype Float but got backend CUDA and dtype Float
```

Could somebody point me in the right direction as to where the code has to be modified to fix this error? 

I feel like its a `.cuda()` addition somewhere. Any help would be appreciated.

**Comment by GrzegorzKarchNV** [comment]
Hi,
I cannot reproduce your error, please check the following:

- your local repo is up to date
- you are running the inference within a Docker container
- you are running the inference from folder 

`DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/`

Let me know if it helps.

**Comment by rakshithvasudev** [comment]
Hello @GrzegorzKarchNV ,

Thanks for the response. It looks like my version of the code was a little behind. I cloned the latest version. It now works. 

Thanks!
