### ISSUE TITLE
Example Compability Issue

### ISSUE THREAD

**Issue by ghostplant** [NVIDIA/DeepLearningExamples#285]
```sh
~/DeepLearningExamples/PyTorch/LanguageModeling/BERT$ python run_pretraining.py
Traceback (most recent call last):
  File "run_pretraining.py", line 38, in <module>
    from apex import amp
  File "/usr/local/lib/python2.7/dist-packages/apex-0.1-py2.7.egg/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/usr/local/lib/python2.7/dist-packages/apex-0.1-py2.7.egg/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/usr/local/lib/python2.7/dist-packages/apex-0.1-py2.7.egg/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/usr/local/lib/python2.7/dist-packages/apex-0.1-py2.7.egg/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/usr/local/lib/python2.7/dist-packages/apex-0.1-py2.7.egg/apex/amp/wrap.py", line 4, in <module>
    from . import rnn_compat
ImportError: cannot import name rnn_compat
```

**Comment by sharathts** [comment]
You have to be in the container in order to do pretraining. Please see steps 3 and 4 in the quick start guide https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/LanguageModeling/BERT#quick-start-guide

**Comment by ghostplant** [comment]
Thanks!
