### ISSUE TITLE
question around transfer learning

### ISSUE THREAD

**Issue by doursand** [NVIDIA/DeepLearningExamples#291]
Hello

I would like to download the weights from nvidia website  for the tacotron2 https://ngc.nvidia.com/catalog/models/nvidia:tacotron2pyt_fp32

What is the process to use this downloaded file to resume the training on my machine ?
thanks in advance

**Comment by doursand** [comment]
more specifically when I try to resume the training from JoC_Tacotron2_FP32_PyT_20190306
using 

`python -m multiproc train.py -m Tacotron2 -o ./output/ --checkpoint-path ./nvidia_tacotron2pyt_fp32_20190427 -lr 1e-3 --epochs 1501 -bs 64 --weight-decay 1e-6 --grad-clip-thresh 1.0 --cudnn-enabled --log-file ./output/nvlog.json --anneal-steps 500 1000 1500 --anneal-factor 0.1 --amp-run`

I end up with this error message 

```
:::NVLOGv0.2.2 Tacotron2_PyT 1573598633.701398611 (/data/home/doursand/ext/repos/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:279) run_start
:::NVLOGv0.2.2 Tacotron2_PyT 1573598633.707500458 (/data/home/doursand/ext/repos/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) cpu_info: {"num": 6, "name": "Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz"}
:::NVLOGv0.2.2 Tacotron2_PyT 1573598633.713320732 (/data/home/doursand/ext/repos/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) mem_info: {"ram": "55G"}
:::NVLOGv0.2.2 Tacotron2_PyT 1573598633.743303061 (/data/home/doursand/ext/repos/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) gpu_info: {"driver_version": "418.87.01", "num": 1, "name": ["Tesla K80"], "mem": ["11441 MiB"]}
:::NVLOGv0.2.2 Tacotron2_PyT 1573598633.745774269 (/data/home/doursand/ext/repos/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) args: {"output_directory": "./output/", "dataset_path": "./", "model_name": "Tacotron2", "log_file": "./output/nvlog.json", "anneal_steps": ["500", "1000", "1500"], "anneal_factor": 0.1, "epochs": 1501, "epochs_per_checkpoint": 1, "checkpoint_path": "./nvidia_tacotron2pyt_fp32_20190427", "seed": 1234, "dynamic_loss_scaling": true, "amp_run": true, "cudnn_enabled": true, "cudnn_benchmark": false, "disable_uniform_initialize_bn_weight": false, "use_saved_learning_rate": false, "learning_rate": 0.001, "weight_decay": 1e-06, "grad_clip_thresh": 1.0, "batch_size": 64, "grad_clip": 5.0, "load_mel_from_disk": false, "training_files": "filelists/ljs_audio_text_train_filelist.txt", "validation_files": "filelists/ljs_audio_text_val_filelist.txt", "text_cleaners": ["english_cleaners"], "max_wav_value": 32768.0, "sampling_rate": 22050, "filter_length": 1024, "hop_length": 256, "win_length": 1024, "mel_fmin": 0.0, "mel_fmax": 8000.0, "rank": 0, "world_size": 1, "dist_url": "tcp://localhost:23456", "group_name": "group_name", "dist_backend": "nccl", "mask_padding": false, "n_mel_channels": 80, "n_symbols": 148, "symbols_embedding_dim": 512, "encoder_kernel_size": 5, "encoder_n_convolutions": 3, "encoder_embedding_dim": 512, "n_frames_per_step": 1, "decoder_rnn_dim": 1024, "prenet_dim": 256, "max_decoder_steps": 2000, "gate_threshold": 0.5, "p_attention_dropout": 0.1, "p_decoder_dropout": 0.1, "decoder_no_early_stopping": false, "attention_rnn_dim": 1024, "attention_dim": 128, "attention_location_n_filters": 32, "attention_location_kernel_size": 31, "postnet_embedding_dim": 512, "postnet_kernel_size": 5, "postnet_n_convolutions": 5}
:::NVLOGv0.2.2 Tacotron2_PyT 1573598633.746232033 (/data/home/doursand/ext/repos/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) run_start
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ImportError('/data/anaconda/envs/torchvision/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/amp_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106Device8validateEv',)
Traceback (most recent call last):
  File "train.py", line 501, in <module>
    main()
  File "train.py", line 350, in main
    args.amp_run, args.checkpoint_path)
  File "train.py", line 202, in load_checkpoint
    torch.cuda.set_rng_state_all(checkpoint['cuda_rng_state_all'])
KeyError: 'cuda_rng_state_all'
```

Indeed, if I look at the pytorch pth, there is no 'cuda_rng_state_all' in the checkpoint

```
model = torch.load('JoC_Tacotron2_FP32_PyT_20190306')
model
```

```
{'epoch': 1500,
 'config': {'mask_padding': False,
  'n_mel_channels': 80,
  'n_symbols': 148,
  'symbols_embedding_dim': 512,
  'encoder_kernel_size': 5,
  'encoder_n_convolutions': 3,
  'encoder_embedding_dim': 512,
  'attention_rnn_dim': 1024,
  'attention_dim': 128,
  'attention_location_n_filters': 32,
  'attention_location_kernel_size': 31,
  'n_frames_per_step': 1,
  'decoder_rnn_dim': 1024,
  'prenet_dim': 256,
  'max_decoder_steps': 1000,
  'gate_threshold': 0.5,
  'p_attention_dropout': 0.1,
  'p_decoder_dropout': 0.1,
  'postnet_embedding_dim': 512,
  'postnet_kernel_size': 5,
  'postnet_n_convolutions': 5,
  'decoder_no_early_stopping': False},
 'state_dict': OrderedDict([('module.embedding.weight',
               tensor([[ 5.3642e-03,  9.2479e-03, -2.7802e-02,  ...,  3.0958e-02,
                        -3.6696e-02, -7.9990e-02],
                       [ 6.4997e-02, -2.4745e-01,  1.6181e-01,  ...,  5.4785e-03,
                        -5.0733e-02, -1.9960e-01],
                       [-2.8874e-02,  2.8415e-02, -1.4812e-02,  ...,  2.5578e-02,
                         2.6850e-04, -1.4286e-01],
...
```

**Comment by doursand** [comment]
Ok i think i fixed the problem.
It turns out that the structure of the checkpoint is slightly different between the pretrained model downloaded from NGC and the one running on my machine at least (missing keys and additional "module." keyword at the beg of each key in the statedict

So I created this function to solve the problem and now it works, I can resume the training from epoch 1501

here it the code I created

```
def correct_checkpoint(pretrained_pth,tacotron2_pth,corrected_pth,amp=True):
    '''
        This function solve a problem with the structure of the nvidia downloaded pretrained model
        which does not match with the structure of the checkpoint during the training of the tacotron2
        (at least the current version deployed on github as of Nov 13th 2019)
        
        INPUT:
            pretrained_pth : path to the NVIDIA pretrained model downloaded from nvidia NGC
            tacotron2_pth : path to the local checkpoint on the machine (I used the first checkpoint generated when training from scratch)
            corrected_pth : path to save the corrected checkpoint
    '''
    #load the first checkpoint generated after starting a training from scratch on the machine
    tacotron2 = torch.load(tacotron2_pth)
    
    #make a copy of pretrained model after loading from file into corrected model
    pretrained = torch.load(pretrained_pth)
    corrected = pretrained

    #add missing keys : 'cuda_rng_state_all', 'random_rng_state', 'optimizer', 'amp'
    corrected['cuda_rng_state_all'] = tacotron2['cuda_rng_state_all']
    corrected['random_rng_state'] = tacotron2['random_rng_state']
    corrected['optimizer'] = tacotron2['optimizer']
    corrected['amp'] = tacotron2['amp']
    
    #rename keys in state_dict as there is an additional "module." at the beg of each key which does not exist in tacotron2 ckpt structure
    new_state_dict = OrderedDict((k.split('module.')[1],v) for k, v in corrected['state_dict'].items())
    
    #replace the state_dict in the corrected model
    corrected['state_dict'] = new_state_dict
    
    #create the checkpoint structure for saving back to disk
    checkpoint = {'epoch': model_copy['epoch'],
                  'cuda_rng_state_all': model_copy['cuda_rng_state_all'],
                  'random_rng_state': model_copy['random_rng_state'],
                  'config': model_copy['config'],
                  'state_dict': model_copy['state_dict'],
                  'optimizer': model_copy['optimizer']}
    if amp_run:
        checkpoint['amp'] = model_copy['amp']
    
    #save to disk
    torch.save(checkpoint,corrected_pth)
```

**Comment by doursand** [comment]
Issue closed ...
