### ISSUE TITLE
ShardDataset

### ISSUE THREAD

**Issue by anmol039w** [NVIDIA/DeepLearningExamples#295]
While freezing the Unet_Medical model I'm facing the below error

Machine Configuration
DGX-1 
Container : nvcr.io/nvidia/tensorflow:19.06-py3

root@0a6ff3b42f46:/workspace/work/unet# python freeze.py --model_dir /workspace/work/unet/ --output_node_name output
2019-11-14 07:34:34.782031: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2194845000 Hz
2019-11-14 07:34:34.787747: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x49ba750 executing computations on platform Host. Devices:
2019-11-14 07:34:34.787792: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): <undefined>, <undefined>
2019-11-14 07:34:36.386291: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x4a87590 executing computations on platform CUDA. Devices:
2019-11-14 07:34:36.386345: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): Tesla V100-SXM2-16GB, Compute Capability 7.0
2019-11-14 07:34:36.386354: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (1): Tesla V100-SXM2-16GB, Compute Capability 7.0
2019-11-14 07:34:36.386378: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (2): Tesla V100-SXM2-16GB, Compute Capability 7.0
2019-11-14 07:34:36.386385: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (3): Tesla V100-SXM2-16GB, Compute Capability 7.0
2019-11-14 07:34:36.386393: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (4): Tesla V100-SXM2-16GB, Compute Capability 7.0
2019-11-14 07:34:36.386399: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (5): Tesla V100-SXM2-16GB, Compute Capability 7.0
2019-11-14 07:34:36.386406: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (6): Tesla V100-SXM2-16GB, Compute Capability 7.0
2019-11-14 07:34:36.386430: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (7): Tesla V100-SXM2-16GB, Compute Capability 7.0
2019-11-14 07:34:36.390396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:06:00.0
totalMemory: 15.75GiB freeMemory: 13.79GiB
2019-11-14 07:34:36.390584: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 1 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:07:00.0
totalMemory: 15.75GiB freeMemory: 13.83GiB
2019-11-14 07:34:36.390709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 2 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:0a:00.0
totalMemory: 15.75GiB freeMemory: 15.44GiB
2019-11-14 07:34:36.390835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 3 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:0b:00.0
totalMemory: 15.75GiB freeMemory: 15.44GiB
2019-11-14 07:34:36.390964: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 4 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:85:00.0
totalMemory: 15.75GiB freeMemory: 15.44GiB
2019-11-14 07:34:36.391124: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 5 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:86:00.0
totalMemory: 15.75GiB freeMemory: 15.44GiB
2019-11-14 07:34:36.391248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 6 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:89:00.0
totalMemory: 15.75GiB freeMemory: 15.44GiB
2019-11-14 07:34:36.391404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 7 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:8a:00.0
totalMemory: 15.75GiB freeMemory: 15.44GiB
2019-11-14 07:34:36.391631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7
2019-11-14 07:34:39.678889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-14 07:34:39.678966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 1 2 3 4 5 6 7
2019-11-14 07:34:39.678976: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N Y Y Y Y N N N
2019-11-14 07:34:39.678984: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 1:   Y N Y Y N Y N N
2019-11-14 07:34:39.678991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 2:   Y Y N Y N N Y N
2019-11-14 07:34:39.679017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 3:   Y Y Y N N N N Y
2019-11-14 07:34:39.679023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 4:   Y N N N N Y Y Y
2019-11-14 07:34:39.679030: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 5:   N Y N N Y N Y Y
2019-11-14 07:34:39.679037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 6:   N N Y N Y Y N Y
2019-11-14 07:34:39.679044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 7:   N N N Y Y Y Y N
2019-11-14 07:34:39.680326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13325 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:06:00.0, compute capability: 7.0)
2019-11-14 07:34:39.680822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 13365 MB memory) -> physical GPU (device: 1, name: Tesla V100-SXM2-16GB, pci bus id: 0000:07:00.0, compute capability: 7.0)
2019-11-14 07:34:39.681099: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 14935 MB memory) -> physical GPU (device: 2, name: Tesla V100-SXM2-16GB, pci bus id: 0000:0a:00.0, compute capability: 7.0)
2019-11-14 07:34:39.681363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 14935 MB memory) -> physical GPU (device: 3, name: Tesla V100-SXM2-16GB, pci bus id: 0000:0b:00.0, compute capability: 7.0)
2019-11-14 07:34:39.681705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 14935 MB memory) -> physical GPU (device: 4, name: Tesla V100-SXM2-16GB, pci bus id: 0000:85:00.0, compute capability: 7.0)
2019-11-14 07:34:39.682022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:5 with 14935 MB memory) -> physical GPU (device: 5, name: Tesla V100-SXM2-16GB, pci bus id: 0000:86:00.0, compute capability: 7.0)
2019-11-14 07:34:39.682452: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:6 with 14935 MB memory) -> physical GPU (device: 6, name: Tesla V100-SXM2-16GB, pci bus id: 0000:89:00.0, compute capability: 7.0)
2019-11-14 07:34:39.682731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:7 with 14935 MB memory) -> physical GPU (device: 7, name: Tesla V100-SXM2-16GB, pci bus id: 0000:8a:00.0, compute capability: 7.0)
Traceback (most recent call last):
  File "freeze.py", line 68, in <module>
    freeze_graph(args.model_dir, args.output_node_names)
  File "freeze.py", line 41, in freeze_graph
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1435, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1457, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 399, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 159, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'ShardDataset'

**Comment by pribalta** [comment]
@anmol039w did you manage to overcome the issue? We have released with UNet scripts to export the model which might help you

**Comment by anmol039w** [comment]
Hey Pribalta thanks for the update , will try the new script and get back to you

**Comment by pribalta** [comment]
@anmol039w any progress on this?

**Comment by anmol039w** [comment]
Hey ,

Don't have the acess to my system due to lockdown, will inform you as soon
as lockdown ends
