### ISSUE TITLE
pytorch bert with fp32

### ISSUE THREAD

**Issue by eric-haibin-lin** [NVIDIA/DeepLearningExamples#298]
When I set precision to fp32 for pytorch bert, I got the following error: 
```

Container nvidia build =  7741716
/workspace/bert/data/hdf5_lower_case_1_seq_len_128_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5_fake_1/books_wiki_en_corpus/
Logs written to /workspace/bert/results/bert_lamb_pretraining.pyt_bert_pretraining_phase1_fp32_gbs64.191115010503.log
+ '[' -z /workspace/bert/results/bert_lamb_pretraining.pyt_bert_pretraining_phase1_fp32_gbs64.191115010503.log ']'
+ tee /workspace/bert/results/bert_lamb_pretraining.pyt_bert_pretraining_phase1_fp32_gbs64.191115010503.log
+ python3 -m torch.distributed.launch --nproc_per_node=1 /workspace/bert/run_pretraining.py --input_dir=/workspace/bert/data/hdf5_lower_case_1_seq_len_128_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5_fake_1/books_wiki_en_corpus/ --output_dir=/workspace/bert/results/checkpoints --config_file=bert_config.json --bert_model=bert-large-uncased --train_batch_size=64 --max_seq_length=128 --max_predictions_per_seq=20 --max_steps=7038 --warmup_proportion=0.2843 --num_steps_per_checkpoint=10 --learning_rate=6e-3 --seed=30639 --gradient_accumulation_steps=1 --allreduce_post_accumulation --do_train
11/15/2019 01:05:04 - INFO - __main__ -   device cuda:0 n_gpu 1 distributed training True
SEED 30639
11/15/2019 01:05:14 - INFO - __main__ -   ***** Running training *****
11/15/2019 01:05:14 - INFO - __main__ -     Batch size = 64
  LR =  0.006
Training. . .
11/15/2019 01:05:14 - INFO - __main__ -   file no 1 file /workspace/bert/data/hdf5_lower_case_1_seq_len_128_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5_fake_1/books_wiki_en_corpus/books_wiki_en_corpus_training_1.hdf5
Iteration:   0%|          | 0/938 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/workspace/bert/run_pretraining.py", line 592, in <module>
    args = main()
  File "/workspace/bert/run_pretraining.py", line 533, in main
    global_step = take_optimizer_step(args, optimizer, model, overflow_buf, global_step)
  File "/workspace/bert/run_pretraining.py", line 359, in take_optimizer_step
    scaler = _amp_state.loss_scalers[0]
AttributeError: 'AmpState' object has no attribute 'loss_scalers'

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-u', '/workspace/bert/run_pretraining.py', '--local_rank=0', '--input_dir=/workspace/bert/data/hdf5_lower_case_1_seq_len_128_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5_fake_1/books_wiki_en_corpus/', '--output_dir=/workspace/bert/results/checkpoints', '--config_file=bert_config.json', '--bert_model=bert-large-uncased', '--train_batch_size=64', '--max_seq_length=128', '--max_predictions_per_seq=20', '--max_steps=7038', '--warmup_proportion=0.2843', '--num_steps_per_checkpoint=10', '--learning_rate=6e-3', '--seed=30639', '--gradient_accumulation_steps=1', '--allreduce_post_accumulation', '--do_train']' returned non-zero exit status 1.
+ set +x
finished pretraining, starting benchmarking
awk: line 1: syntax error at or near *
 training throughput phase1:  sequences/second
average loss:
final loss:

```

**Comment by sharathts** [comment]
`--allreduce_post_accumulation` option is not supported with fp32. You will have to turn it off to run fp32.

**Comment by eric-haibin-lin** [comment]
thanks!
