### ISSUE TITLE
Problems and solutions to unning WMT14 English-German examples with Transformer

### ISSUE THREAD

**Issue by hwansoo** [NVIDIA/DeepLearningExamples#305]
If I just follow the instructions in the Quick Start sections of https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Translation/Transformer with nvcr.io/nvidia/pytorch:19.06-py3, during training with the WMT14 English-German dataset, I run into the following problem.

```
python train.py /data/wmt14_en_de_joined_dict \
>   --arch transformer_wmt_en_de_big_t2t \
>   --share-all-embeddings \
>   --optimizer adam \
>   --adam-betas '(0.9, 0.997)' \
>   --adam-eps "1e-9" \
>   --clip-norm 0.0 \
>   --lr-scheduler inverse_sqrt \
>   --warmup-init-lr 0.0 \
>   --warmup-updates 4000 \
>   --lr 0.0006 \
>   --min-lr 0.0 \
>   --dropout 0.1 \
>   --weight-decay 0.0 \
>   --criterion label_smoothed_cross_entropy \
>   --label-smoothing 0.1 \
>   --max-tokens 5120 \
>   --seed 1 \
>   --target-bleu 25 \
>   --ignore-case \
>   --fp16 \
>   --save-dir /workspace/checkpoints
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    from fairseq import data, distributed_utils, options, progress_bar, tasks, utils, bleu, tokenizer
  File "/workspace/translation/fairseq/options.py", line 28, in <module>
    from fairseq.models import ARCH_MODEL_REGISTRY, ARCH_CONFIG_REGISTRY
  File "/workspace/translation/fairseq/models/__init__.py", line 63, in <module>
    importlib.import_module('fairseq.models.' + module)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workspace/translation/fairseq/models/fused_relu_dropout.py", line 16, in <module>
    import fused_relu_dropout_cuda
ModuleNotFoundError: No module named 'fused_relu_dropout_cuda'
```

To solve the problem, we have to add the following lines to the setup.py, 
```
# fused_dropout_add and fused_relu_dropout are copied from https://github.com/mlperf/training_results_v0.5/blob/master/v0.5.0/nvidia/submission/code/translation/pytorch/setup.py
fused_dropout_add = CUDAExtension(
                        name='fused_dropout_add_cuda',
                        sources=['fairseq/models/fused_dropout_add/fused_dropout_add_cuda.cpp', 'fairseq/models/fused_dropout_add/fused_dropout_add_cuda_kernel.cu'],
                        extra_compile_args={
                                'cxx': ['-O2',],
                                'nvcc':['--gpu-architecture=sm_70','-O3','--use_fast_math', '--expt-extended-lambda'],
                        }
)
fused_relu_dropout = CUDAExtension(
                        name='fused_relu_dropout_cuda',
                        sources=['fairseq/models/fused_relu_dropout/fused_relu_dropout_cuda.cpp', 'fairseq/models/fused_relu_dropout/fused_relu_dropout_cuda_kernel.cu'],
                        extra_compile_args={
                                'cxx': ['-O2',],
                                'nvcc':['--gpu-architecture=sm_70','-O3','--use_fast_math', '--expt-extended-lambda'],
                        }
)
```
and change the following line
```
ext_modules=[bleu, strided_batched_gemm, batch_utils],
```
to 
```    
ext_modules=[bleu, strided_batched_gemm, fused_dropout_add, fused_relu_dropout, batch_utils],
```

Another  thing to do is to use an older version of apex to solve the fused adam problem.
Changing the following lines in the Dockerfile
```
RUN git clone https://github.com/NVIDIA/apex \
 && cd apex \
 && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
to 
```
RUN git clone https://github.com/NVIDIA/apex \
 && cd apex \
 && git reset --hard adad599616bc14892f4ebf19948e07a9bd6e0ee2 \
 && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
worked.

The above solutions is resolving the issues by reverting some of the code to the older version, so I wouldn't recommend updating the current code to this version, but if there's anyone interested in running the transformer with the current version of this repo, here's a way to work around the problems.

**Comment by nv-kkudrynski** [comment]
Problem already resolved.
