### ISSUE TITLE
BioBERT TensorFlow Data download & Preprocess error "ValueError: /workspace/bert/data/sharded/pubmed_baseline/training/pubmed_baseline_training_2.txt is not a valid path"

### ISSUE THREAD

**Issue by Montantes** [NVIDIA/DeepLearningExamples#316]
Below is a sample of an error I get during the `bash scripts/data_download.sh` phase. Is anyone else getting this? 

2019-11-23 08:24:19.330801: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2019-11-23 08:24:19.330814: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2019-11-23 08:24:19.330807: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2019-11-23 08:24:19.330799: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2019-11-23 08:24:19.330830: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
Traceback (most recent call last):
  File "/workspace/bert/utils/create_pretraining_data.py", line 501, in <module>
  File "/workspace/bert/utils/create_pretraining_data.py", line 501, in <module>
    main()
    main()
  File "/workspace/bert/utils/create_pretraining_data.py", line 482, in main
  File "/workspace/bert/utils/create_pretraining_data.py", line 482, in main
    raise ValueError("{} is not a valid path".format(args.input_file))
    raise ValueError("{} is not a valid path".format(args.input_file))
ValueError: /workspace/bert/data/sharded/pubmed_baseline/training/pubmed_baseline_training_2.txt is not a valid path
ValueError: /workspace/bert/data/sharded/pubmed_baseline/training/pubmed_baseline_training_1.txt is not a valid path
Traceback (most recent call last):
  File "/workspace/bert/utils/create_pretraining_data.py", line 501, in <module>
Traceback (most recent call last):
  File "/workspace/bert/utils/create_pretraining_data.py", line 501, in <module>
    main()
  File "/workspace/bert/utils/create_pretraining_data.py", line 482, in main
Traceback (most recent call last):
  File "/workspace/bert/utils/create_pretraining_data.py", line 501, in <module>
    raise ValueError("{} is not a valid path".format(args.input_file))
ValueError: /workspace/bert/data/sharded/pubmed_baseline/training/pubmed_baseline_training_0.txt is not a valid path
    main()
  File "/workspace/bert/utils/create_pretraining_data.py", line 482, in main
    raise ValueError("{} is not a valid path".format(args.input_file))
ValueError: /workspace/bert/data/sharded/pubmed_baseline/training/pubmed_baseline_training_4.txt is not a valid path
    main()
  File "/workspace/bert/utils/create_pretraining_data.py", line 482, in main
    raise ValueError("{} is not a valid path".format(args.input_file))
ValueError: /workspace/bert/data/sharded/pubmed_baseline/training/pubmed_baseline_training_3.txt is not a valid path

**Comment by swethmandava** [comment]
it looks like it can't find those files or the permissions aren't correct?! Can you try 'ls -al  /workspace/bert/data/sharded/pubmed_baseline/training/'

**Comment by Montantes** [comment]
root@ubuntu:/workspace/bert# ls -al /workspace/bert/data/sharded/pubmed_baseline/training/
total 8
drwxr-xr-x 2 root root 4096 Nov 23 08:21 .
drwxr-xr-x 4 root root 4096 Nov 23 08:21 ..

**Comment by swethmandava** [comment]
Looks like the file pubmed_baseline_training_3.txt is not there. Can you retry and send the full log? I'm not sure if it errored out while writing the files in the first place.
