### ISSUE TITLE
train.tsv file? TensorFlow BioBERT Benchmark Testing error tensorflow.python.framework.errors_impl.NotFoundError: /workspace/bert/data/biobert/BC5CDR/disease/train.tsv; No such file or directory

### ISSUE THREAD

**Issue by Montantes** [NVIDIA/DeepLearningExamples#323]
(note: logs attached) 
when running train benchmark command

` bash biobert/scripts/biobert_finetune_train_benchmark.sh ner_bc5cdr-disease 2 base true`

i get the error:

tensorflow.python.framework.errors_impl.NotFoundError: /workspace/bert/data/biobert/BC5CDR/disease/train.tsv; No such file or directory
Traceback (most recent call last):
  File "/workspace/bert/run_ner.py", line 872, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/workspace/bert/run_ner.py", line 684, in main
    train_examples = processor.get_train_examples(FLAGS.data_dir)
  File "/workspace/bert/run_ner.py", line 212, in get_train_examples
    l1 = self._read_data(os.path.join(data_dir, "train.tsv"))
  File "/workspace/bert/run_ner.py", line 175, in _read_data
    for line in f:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 220, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 214, in next
    retval = self.readline()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 178, in readline
    self._preread_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: /workspace/bert/data/biobert/BC5CDR/disease/train.tsv; No such file or directory
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[31235,1],1]
  Exit code:    1

[ner_bc5cdr-disease_training_benchmark.log](https://github.com/NVIDIA/DeepLearningExamples/files/3907499/ner_bc5cdr-disease_training_benchmark.log)
[ner_bc5cdr-disease_training_benchmark.log](https://github.com/NVIDIA/DeepLearningExamples/files/3907500/ner_bc5cdr-disease_training_benchmark.log)
[ner_bc5cdr-disease_training_benchmark.log](https://github.com/NVIDIA/DeepLearningExamples/files/3907501/ner_bc5cdr-disease_training_benchmark.log)
[ner_bc5cdr-disease_training_benchmark.log](https://github.com/NVIDIA/DeepLearningExamples/files/3907502/ner_bc5cdr-disease_training_benchmark.log)

**Comment by Montantes** [comment]
I realized I didn't download/unzip to right directory, can close for now.
