### ISSUE TITLE
ModuleNotFoundError: No module named 'fairseq.data.batch_C'

### ISSUE THREAD

**Issue by romanzj** [NVIDIA/DeepLearningExamples#35]
Hello,

When running "run_preprocessing.sh", no module "batch_C" in fairseq/data within  DeepLearningExamples/PyTorch/Translation/Transformer directory. 

Anybody with a suggestion ? 
R.

Traceback (most recent call last):
  File "preprocess.py", line 15, in <module>
    from fairseq.data import indexed_dataset, dictionary
  File "/bfs/hpc_cluster/work/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/data/__init__.py", line 26, in <module>
    from .language_pair_dataset import LanguagePairDataset
  File "/bfs/hpc_cluster/work/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/data/language_pair_dataset.py", line 26, in <module>
    from . import data_utils, FairseqDataset
  File "/bfs/hpc_cluster/work/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/data/data_utils.py", line 31, in <module>
    import fairseq.data.batch_C
ModuleNotFoundError: No module named 'fairseq.data.batch_C'

**Comment by jbaczek** [comment]
Hi, have you built your container with the Dockerfile provided in repository?

**Comment by nvpstr** [comment]
It should work with the container build with the provided Dockerfile.

**Comment by asispatra** [comment]
@nvpstr , I am getting this issue, where I got the dockar image from NVIDIA NGC. 
```
docker pull nvcr.io/nvidia/pytorch:19.05-py3
```
How to resolve this?

Thanks.

**Comment by jbaczek** [comment]
It is probably because you lack the cutlass submodule (for whatever reason). If you clone this repository, remember to include `--recurse-submodules` option. If this happens with the code inclused in the container, please post how to reprodude the bug step by step
