### ISSUE TITLE
Vnet, change input_shape

### ISSUE THREAD

**Issue by jefflgaol** [NVIDIA/DeepLearningExamples#440]
Hi, there! Right now, I'm trying to use the DeepLearningExamples: Vnet. The example worked perfectly when I executed it using default parameter of input_shape which is [32 32 32] and with Hippocampus dataset. However, when I tried it with another dataset, and when I changed the input_shape into [96 96 96], it showed some error like this:
```
DLL 2020-04-02 11:57:57.735685 - PARAMETER exec_mode : train_and_evaluate 
DLL 2020-04-02 11:57:57.735740 - PARAMETER data_normalization : zscore 
DLL 2020-04-02 11:57:57.735756 - PARAMETER activation : relu 
DLL 2020-04-02 11:57:57.735768 - PARAMETER resize_interpolator : linear 
DLL 2020-04-02 11:57:57.735779 - PARAMETER loss : dice 
DLL 2020-04-02 11:57:57.735790 - PARAMETER normalization_layer : batchnorm 
DLL 2020-04-02 11:57:57.735802 - PARAMETER pooling : conv_pool 
DLL 2020-04-02 11:57:57.735813 - PARAMETER upsampling : transposed_conv 
DLL 2020-04-02 11:57:57.735824 - PARAMETER seed : 0 
DLL 2020-04-02 11:57:57.735837 - PARAMETER input_shape : [96, 96, 96] 
DLL 2020-04-02 11:57:57.735870 - PARAMETER upscale_blocks : [3, 3] 
DLL 2020-04-02 11:57:57.735882 - PARAMETER downscale_blocks : [3, 3, 3] 
DLL 2020-04-02 11:57:57.735894 - PARAMETER convolution_size : 5 
DLL 2020-04-02 11:57:57.735905 - PARAMETER batch_size : 4 
DLL 2020-04-02 11:57:57.735917 - PARAMETER log_every : 10 
DLL 2020-04-02 11:57:57.735928 - PARAMETER warmup_steps : 200 
DLL 2020-04-02 11:57:57.735939 - PARAMETER train_epochs : 260 
DLL 2020-04-02 11:57:57.735951 - PARAMETER optimizer : rmsprop 
DLL 2020-04-02 11:57:57.735969 - PARAMETER gradient_clipping : global_norm 
DLL 2020-04-02 11:57:57.735984 - PARAMETER base_lr : 0.0001 
DLL 2020-04-02 11:57:57.736006 - PARAMETER momentum : 0.0 
DLL 2020-04-02 11:57:57.736039 - PARAMETER train_split : 0.9 
DLL 2020-04-02 11:57:57.736057 - PARAMETER split_seed : 42 
DLL 2020-04-02 11:57:57.736072 - PARAMETER model_dir : ./tmp 
DLL 2020-04-02 11:57:57.736089 - PARAMETER log_dir : None 
DLL 2020-04-02 11:57:57.736106 - PARAMETER data_dir : ./data2/ 
DLL 2020-04-02 11:57:57.736119 - PARAMETER benchmark : False 
DLL 2020-04-02 11:57:57.736132 - PARAMETER use_amp : False 
DLL 2020-04-02 11:57:57.736144 - PARAMETER augment : True 
2020-04-02 11:58:31.561146: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-02 11:58:31.578504: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-02 11:58:31.578946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
2020-04-02 11:58:31.578961: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
2020-04-02 11:58:31.580267: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-02 11:58:31.581393: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-04-02 11:58:31.581667: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-04-02 11:58:31.582969: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-04-02 11:58:31.583778: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-04-02 11:58:31.586339: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-02 11:58:31.586503: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-02 11:58:31.586997: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-02 11:58:31.587385: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 131072 elements to shape [4,96,96,96,1] (3538944 elements) for 'vnet/Reshape' (op: 'Reshape') with input shapes: [4,32,32,32], [5] and with input tensors computed as partial shapes: input[1] = [4,96,96,96,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/vnet/DOCKER_CONNECTOR/inside/main.py", line 165, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/workspace/vnet/DOCKER_CONNECTOR/inside/main.py", line 126, in main
    hooks=train_hooks)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1191, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/workspace/vnet/DOCKER_CONNECTOR/inside/utils/model_fn.py", line 49, in vnet_v2
    [params.batch_size] + params.input_shape + [1])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 131, in reshape
    result = gen_array_ops.reshape(tensor, shape, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 8115, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Cannot reshape a tensor with 131072 elements to shape [4,96,96,96,1] (3538944 elements) for 'vnet/Reshape' (op: 'Reshape') with input shapes: [4,32,32,32], [5] and with input tensors computed as partial shapes: input[1] = [4,96,96,96,1].
```
Do you have any suggestions on how to resolve this issue? Or I simply can't change the input_shape? Thank you.
Note: my dataset size is 96x512x512 (z-stack, height, width).

**Comment by pribalta** [comment]
Hi @jefflgaol,

From the trace I see that there is a mismatch in the tensor dimensions:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 131072 elements to shape [4,96,96,96,1] (3538944 elements) for 'vnet/Reshape' (op: 'Reshape') with input shapes: [4,32,32,32], [5] and with input tensors computed as partial shapes: input[1] = [4,96,96,96,1].
```
Above, the input expects a 4D-tensor of shape

**Comment by pribalta** [comment]
Hi @jefflgaol , I will look at the issue. Seems like something could be changed in the data loader in order to facilitate what you want to accomplish

**Comment by jefflgaol** [comment]
Oh, I see. As it turns out, when I changed the data loader as per your suggestion, I am able to train the model. Thank you.
