### ISSUE TITLE
[FastTransformer/v2] run translate_sample.py with batch_size=16 failed.

### ISSUE THREAD

**Issue by duduscript** [NVIDIA/DeepLearningExamples#452]
Related to **FastTransformer/v2** 
*FasterTransformer/v2*

**Describe the bug**
run translate_sample.py with batch_size=16 failed.
`
2020-04-08 14:29:42.124155: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-04-08 14:29:43.819479: I tensorflow/stream_executor/platform/default/dso_
loader.cc:42] Successfully opened dynamic library libcublas.so.10
Traceback (most recent call last):
  File "translate_sample.py", line 248, in <module>
    sess.run([op_target_tokens, op_target_length, source])                      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/sessio
n.py", line 950, in run
    run_metadata_ptr)                                                           File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/sessio
n.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)                                    File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/sessio
n.py", line 1350, in _do_run
    run_metadata)                                                               File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/sessio
n.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)                                      tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s)
found.
  (0) Invalid argument: Input to reshape is a tensor with 264192 values, but t
he requested shape requires a multiple of 8192                                         [[node Reshape (defined at translate_sample.py:143) ]]
         [[Minimum_3/_761]]
  (1) Invalid argument: Input to reshape is a tensor with 264192 values, but t
he requested shape requires a multiple of 8192
         [[node Reshape (defined at translate_sample.py:143) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.                           Input Source operations connected to node Reshape:
 transformer/encoder/LayerNorm/batchnorm/add_1 (defined at /usr/local/lib/pyth
on2.7/dist-packages/opennmt/layers/transformer.py:324)
Input Source operations connected to node Reshape:
 transformer/encoder/LayerNorm/batchnorm/add_1 (defined at /usr/local/lib/python2.7/dist-packages/opennmt/layers/transformer.py:324)

Original stack trace for u'Reshape':                                            File "translate_sample.py", line 143, in <module>
    tf_encoder_result, [batch_size, -1, encoder_hidden_dim])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 7715, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_
def_library.py", line 788, in _apply_op_helper                                    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecat
ion.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops
.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops
.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

`

**To Reproduce**
1. enter docker and build fasttransformer
2. ./bin/decoding_gemm 16 4 8 64 32001 100 512 0
2. python translate_sample.py --batch_size=16

**Expected behavior**

**Environment**
Please provide at least:
* docker: nvcr.io/nvidia/tensorflow:19.07-py2

**Comment by byshiue** [comment]
Can you try the lastes version, v3.1?
