### ISSUE TITLE
[Tacotron2] Transfer learning

### ISSUE THREAD

**Issue by dmitrytyrin** [NVIDIA/DeepLearningExamples#467]
Hello!
Is it possible to fine-tune tacotron2 for non-english language?

I tried to start training with flag --checkpoint-path /path/to/tacotron2_1032590_6000_amp (checkpoint downloaded from https://ngc.nvidia.com/catalog/models/nvidia:tacotron2pyt_fp16/files?version=3)
This gives me error:
```
Traceback (most recent call last):
  File "train.py", line 501, in <module>
    main()
  File "train.py", line 357, in main
    args.amp_run, args.checkpoint_path, local_rank)
  File "train.py", line 206, in load_checkpoint
    model.load_state_dict(checkpoint['state_dict'])
  File "/data/user/dmt/work_dir/venv_tts/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron2:
        Missing key(s) in state_dict: "embedding.weight", "encoder.convolutions.0.0.conv.weight", "encoder.convolutions.0.0.conv.bias", "encoder.convolutions.0.1.weight", "encoder.convolutions.0.1.bias", "encoder.convolutions.0.1.running_mean", "encoder.convolutions.0.1.running_var", "encoder.convolutions.1.0.conv.weight", "encoder.convolutions.1.0.conv.bias", "encoder.convolutions.1.1.weight", "encoder.convolutions.1.1.bias", "encoder.convolutions.1.1.running_mean", "encoder.convolutions.1.1.running_var", "encoder.convolutions.2.0.conv.weight", "encoder.convolutions.2.0.conv.bias", "encoder.convolutions.2.1.weight", "encoder.convolutions.2.1.bias", "encoder.convolutions.2.1.running_mean", "encoder.convolutions.2.1.running_var", "encoder.lstm.weight_ih_l0", "encoder.lstm.weight_hh_l0", "encoder.lstm.bias_ih_l0", "encoder.lstm.bias_hh_l0", "encoder.lstm.weight_ih_l0_reverse", "encoder.lstm.weight_hh_l0_reverse", "encoder.lstm.bias_ih_l0_reverse", "encoder.lstm.bias_hh_l0_reverse", "decoder.prenet.layers.0.linear_layer.weight", "decoder.prenet.layers.1.linear_layer.weight", "decoder.attention_rnn.weight_ih", "decoder.attention_rnn.weight_hh", "decoder.attention_rnn.bias_ih", "decoder.attention_rnn.bias_hh", "decoder.attention_layer.query_layer.linear_layer.weight", "decoder.attention_layer.memory_layer.linear_layer.weight", "decoder.attention_layer.v.linear_layer.weight", "decoder.attention_layer.location_layer.location_conv.conv.weight", "decoder.attention_layer.location_layer.location_dense.linear_layer.weight", "decoder.decoder_rnn.weight_ih", "decoder.decoder_rnn.weight_hh", "decoder.decoder_rnn.bias_ih", "decoder.decoder_rnn.bias_hh", "decoder.linear_projection.linear_layer.weight", "decoder.linear_projection.linear_layer.bias", "decoder.gate_layer.linear_layer.weight", "decoder.gate_layer.linear_layer.bias", "postnet.convolutions.0.0.conv.weight", "postnet.convolutions.0.0.conv.bias", "postnet.convolutions.0.1.weight", "postnet.convolutions.0.1.bias", "postnet.convolutions.0.1.running_mean", "postnet.convolutions.0.1.running_var", "postnet.convolutions.1.0.conv.weight", "postnet.convolutions.1.0.conv.bias", "postnet.convolutions.1.1.weight", "postnet.convolutions.1.1.bias", "postnet.convolutions.1.1.running_mean", "postnet.convolutions.1.1.running_var", "postnet.convolutions.2.0.conv.weight", "postnet.convolutions.2.0.conv.bias", "postnet.convolutions.2.1.weight", "postnet.convolutions.2.1.bias", "postnet.convolutions.2.1.running_mean", "postnet.convolutions.2.1.running_var", "postnet.convolutions.3.0.conv.weight", "postnet.convolutions.3.0.conv.bias", "postnet.convolutions.3.1.weight", "postnet.convolutions.3.1.bias", "postnet.convolutions.3.1.running_mean", "postnet.convolutions.3.1.running_var", "postnet.convolutions.4.0.conv.weight", "postnet.convolutions.4.0.conv.bias", "postnet.convolutions.4.1.weight", "postnet.convolutions.4.1.bias", "postnet.convolutions.4.1.running_mean", "postnet.convolutions.4.1.running_var".
        Unexpected key(s) in state_dict: "module.embedding.weight", "module.encoder.convolutions.0.0.conv.weight", "module.encoder.convolutions.0.0.conv.bias", "module.encoder.convolutions.0.1.weight", "module.encoder.convolutions.0.1.bias", "module.encoder.convolutions.0.1.running_mean", "module.encoder.convolutions.0.1.running_var", "module.encoder.convolutions.0.1.num_batches_tracked", "module.encoder.convolutions.1.0.conv.weight", "module.encoder.convolutions.1.0.conv.bias", "module.encoder.convolutions.1.1.weight", "module.encoder.convolutions.1.1.bias", "module.encoder.convolutions.1.1.running_mean", "module.encoder.convolutions.1.1.running_var", "module.encoder.convolutions.1.1.num_batches_tracked", "module.encoder.convolutions.2.0.conv.weight", "module.encoder.convolutions.2.0.conv.bias", "module.encoder.convolutions.2.1.weight", "module.encoder.convolutions.2.1.bias", "module.encoder.convolutions.2.1.running_mean", "module.encoder.convolutions.2.1.running_var", "module.encoder.convolutions.2.1.num_batches_tracked", "module.encoder.lstm.weight_ih_l0", "module.encoder.lstm.weight_hh_l0", "module.encoder.lstm.bias_ih_l0", "module.encoder.lstm.bias_hh_l0", "module.encoder.lstm.weight_ih_l0_reverse", "module.encoder.lstm.weight_hh_l0_reverse", "module.encoder.lstm.bias_ih_l0_reverse", "module.encoder.lstm.bias_hh_l0_reverse", "module.decoder.prenet.layers.0.linear_layer.weight", "module.decoder.prenet.layers.1.linear_layer.weight", "module.decoder.attention_rnn.weight_ih", "module.decoder.attention_rnn.weight_hh", "module.decoder.attention_rnn.bias_ih", "module.decoder.attention_rnn.bias_hh", "module.decoder.attention_layer.query_layer.linear_layer.weight", "module.decoder.attention_layer.memory_layer.linear_layer.weight", "module.decoder.attention_layer.v.linear_layer.weight", "module.decoder.attention_layer.location_layer.location_conv.conv.weight", "module.decoder.attention_layer.location_layer.location_dense.linear_layer.weight", "module.decoder.decoder_rnn.weight_ih", "module.decoder.decoder_rnn.weight_hh", "module.decoder.decoder_rnn.bias_ih", "module.decoder.decoder_rnn.bias_hh", "module.decoder.linear_projection.linear_layer.weight", "module.decoder.linear_projection.linear_layer.bias", "module.decoder.gate_layer.linear_layer.weight", "module.decoder.gate_layer.linear_layer.bias", "module.postnet.convolutions.0.0.conv.weight", "module.postnet.convolutions.0.0.conv.bias", "module.postnet.convolutions.0.1.weight", "module.postnet.convolutions.0.1.bias", "module.postnet.convolutions.0.1.running_mean", "module.postnet.convolutions.0.1.running_var", "module.postnet.convolutions.0.1.num_batches_tracked", "module.postnet.convolutions.1.0.conv.weight", "module.postnet.convolutions.1.0.conv.bias", "module.postnet.convolutions.1.1.weight", "module.postnet.convolutions.1.1.bias", "module.postnet.convolutions.1.1.running_mean", "module.postnet.convolutions.1.1.running_var", "module.postnet.convolutions.1.1.num_batches_tracked", "module.postnet.convolutions.2.0.conv.weight", "module.postnet.convolutions.2.0.conv.bias", "module.postnet.convolutions.2.1.weight", "module.postnet.convolutions.2.1.bias", "module.postnet.convolutions.2.1.running_mean", "module.postnet.convolutions.2.1.running_var", "module.postnet.convolutions.2.1.num_batches_tracked", "module.postnet.convolutions.3.0.conv.weight", "module.postnet.convolutions.3.0.conv.bias", "module.postnet.convolutions.3.1.weight", "module.postnet.convolutions.3.1.bias", "module.postnet.convolutions.3.1.running_mean", "module.postnet.convolutions.3.1.running_var", "module.postnet.convolutions.3.1.num_batches_tracked", "module.postnet.convolutions.4.0.conv.weight", "module.postnet.convolutions.4.0.conv.bias", "module.postnet.convolutions.4.1.weight", "module.postnet.convolutions.4.1.bias", "module.postnet.convolutions.4.1.running_mean", "module.postnet.convolutions.4.1.running_var", "module.postnet.convolutions.4.1.num_batches_tracked".
```

**Comment by GrzegorzKarchNV** [comment]
Hi @dmitrytyrin, from the error message I guess you want to fine-tune using 1 GPU. 
In function `load_checkpoint` in `train.py` try replacing 
`model.load_state_dict(checkpoint['state_dict'])` with
```bash
from inference import unwrap_distributed
state_dict = unwrap_distributed(checkpoint['state_dict'])
model.load_state_dict(state_dict)
```

Let me know if it works

**Comment by dmitrytyrin** [comment]
Now I got this error:
```
Traceback (most recent call last):
  File "train.py", line 507, in <module>
    main()
  File "train.py", line 363, in main
    args.amp_run, args.checkpoint_path, local_rank)
  File "train.py", line 211, in load_checkpoint
    model.load_state_dict(state_dict)
  File "/data/user/dmt/work_dir/venv_tts/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron2:
        size mismatch for embedding.weight: copying a param with shape torch.Size([148, 512]) from checkpoint, the shape in current model is torch.Size([156, 512]).
```
I also changed symbols.py (to match my alphabet) and used "basic_cleaners" in ```--text-cleaners``` flag during traing.

**Comment by machineko** [comment]
You can just change emmbeding layer to dont be loaded from checkpoint or add ur own embedding layer after loading checkpoint as pre layer.
(Im using master branch right now and @GrzegorzKarchNV solution was enough for tacotron2_1032590_6000_amp checkpoint with english cleaners)

**Comment by dmitrytyrin** [comment]
@machineko, can you please share how to load all layers except embedding?
```model.load_state_dict(state_dict)``` loads whole checkpoint.

**Comment by machineko** [comment]
You have access to state_dict in code just edit values or in unwrap_distributed method or just in load_checkpoint.
