### ISSUE TITLE
BERT pretraining custom dataset: Target N is out of bounds.

### ISSUE THREAD

**Issue by hajdurobert92** [NVIDIA/DeepLearningExamples#578]
Azure/PyTorch

After having made custom datasets following the guide, keep getting the error below. The dataset has the same format as wiki en corpus.

```
The experiment failed. Finalizing run...
Traceback (most recent call last):
  File "run_pretraining_ort.py", line 552, in <module>
    args, final_loss, train_time_raw = main()
  File "run_pretraining_ort.py", line 481, in main
    loss, global_step = ort_supplement.run_ort_training_step(args, global_step, training_steps, model, batch)
  File "/mnt/batch/tasks/shared/LS_root/jobs/bert-pretraining/azureml/nvbert-ort-pretraining-phase1_1593357051_228e2a81/mounts/workspaceblobstore/azureml/nvbert-ort-pretraining-phase1_1593357051_228e2a81/ort_supplement/ort_supplement.py", line 143, in run_ort_training_step
    loss = model.train_step(input_ids, segment_ids, input_mask, masked_lm_labels, next_sentence_labels, learning_rate, loss_scale)
  File "/opt/miniconda/lib/python3.7/site-packages/onnxruntime/capi/ort_trainer.py", line 786, in train_step
    self._init_onnx_model(sample_input)
  File "/opt/miniconda/lib/python3.7/site-packages/onnxruntime/capi/ort_trainer.py", line 662, in _init_onnx_model
    self.torch_model_, self.loss_fn_, self.model_desc_, torch.device('cpu'), inputs, opset_version=self.opset_version_)
  File "/opt/miniconda/lib/python3.7/site-packages/onnxruntime/capi/ort_trainer.py", line 302, in convert_model_loss_fn_to_onnx
    sample_outputs = model(*sample_inputs)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "run_pretraining_ort.py", line 134, in forward
    return self.loss_fn_(preds_score, seq_relation_score, masked_lm_labels, next_sentence_labels)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "run_pretraining_ort.py", line 119, in forward
    masked_lm_loss = self.loss_fn(prediction_scores.view([self.batch_size * self.seq_length, self.vocab_size]), masked_lm_labels.view(self.batch_size * self.seq_length))
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 932, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/functional.py", line 2317, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/functional.py", line 2115, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
IndexError: Target 105992 is out of bounds.
```

Running on 1 node with 4gpus with onnx.

Any ideas?

Image name is 

'_mcr.microsoft.com/azureml/onnxruntime-training:0.1-rc1-openmpi4.0-cuda10.1-cudnn7.6-nccl2.4.8_'

Regards,
Robert

**Comment by hajdurobert92** [comment]
Wrong configuration might be. Now _Failed to allocate memory for requested buffer of size 16808100352. On Tesla V100 cluster.
