### ISSUE TITLE
[Bert/Pytorch] unhandled system error, NCCL version 2.6.3?

### ISSUE THREAD

**Issue by goyalankit** [NVIDIA/DeepLearningExamples#581]
Related to **Model/Framework(s)** 
*(e.g. GNMT/PyTorch or FasterTransformer/All) BERT/PyTorch

**Describe the bug**
We are trying to train the Bert Pytorch model. Increasing the number of GPUs from 4 to 6 leads to this error:

```
loss_scale             : dynamic
Traceback (most recent call last):
  File "/workspace/bert/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 640, in <module>
    args, final_loss, train_time_raw = main()
  File "/workspace/bert/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 478, in main
    model, optimizer, lr_scheduler, checkpoint, global_step, criterion = prepare_model_and_optimizer(args, device)
  File "/workspace/bert/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 393, in prepare_model_and_optimizer
    flat_dist_call([param.data for param in model.parameters()], torch.distributed.broadcast, (0,) )
  File "/opt/conda/lib/python3.6/site-packages/apex/parallel/distributed.py", line 75, in flat_dist_call
    apply_flat_dist_call(bucket, call, extra_args)
  File "/opt/conda/lib/python3.6/site-packages/apex/parallel/distributed.py", line 41, in apply_flat_dist_call
    call(coalesced, *extra_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 804, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:514, unhandled system error, NCCL version 2.6.3
```

**To Reproduce**
This most likely looks like an environment issue. Simply increasing the num-gpus from 4 to 6 causes this issue.

**Expected behavior**
Training should continue with 6 gpus.

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): nvidia/pytorch:20.03-py3
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): Tesla V100
* CUDA driver version (e.g. 418.67): Driver Version: 418.67       CUDA Version: 10.1

**Comment by slayton58** [comment]
Can you provide the full command line used please?

**Comment by roarjn** [comment]
Could you also provide trace with `NCCL_DEBUG=INFO` flag. [Example](https://github.com/NVIDIA/DeepLearningExamples/issues/51 ) usage of `NCCL_DEBUG`.

**Comment by sharathts** [comment]
Closing since no activity.
