### ISSUE TITLE
Resnet18 is invalid.

### ISSUE THREAD

**Issue by HisiFish** [NVIDIA/DeepLearningExamples#6]
file:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/Classification/imagenet/nvcnn_hvd.py

error log:
```
Traceback (most recent call last):
  File "nvcnn_hvd.py", line 1451, in <module>
    main()
  File "nvcnn_hvd.py", line 1320, in main
    batch_size)
  File "nvcnn_hvd.py", line 522, in training_step
    loss, logits = self.loss_func(images, labels, var_scope)
  File "nvcnn_hvd.py", line 1282, in loss_func
    output = model_func(net, images)
  File "nvcnn_hvd.py", line 1249, in <lambda>
    model_func = lambda net, images: inference_resnet_v1(net, images, nlayer)
  File "nvcnn_hvd.py", line 894, in inference_resnet_v1
    if   nlayer ==  18: return inference_resnet_v1_basic_impl(net, input_layer, [2,2, 2,2])
  File "nvcnn_hvd.py", line 881, in inference_resnet_v1_basic_impl
    basic_resnet_bottleneck_callback = partial(resnet_bottleneck_v1, basic=True)
NameError: name 'partial' is not defined
```

**Comment by nluehr** [comment]
For resnet 18 you need to add the following python import line.

from functools import partial

Note that only the ResNet50 and InceptionV3 examples have been extensively validated. You are welcome to modify nvcnn_hvd.py to enable other networks, but you will want to double check their implementations match your expectation.
