### ISSUE TITLE
[FastPitch/Pytorch] Recipe for train FastPitch for non-english language. 

### ISSUE THREAD

**Issue by dmitrytyrin** [NVIDIA/DeepLearningExamples#658]
Hello!
Following instructions https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/FastPitch I am trying to extract mels using extract_mels.py (without ```--tacotron2-checkpoint```) and get error:
```
Traceback (most recent call last):
  File "extract_mels.py", line 290, in <module>
    main()
  File "extract_mels.py", line 222, in main
    for i, batch in enumerate(data_loader):
  File "/exp_fastpitch/venv/lib64/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/exp_fastpitch/venv/lib64/python3.6/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/exp_fastpitch/venv/lib64/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/exp_fastpitch/venv/lib64/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "extract_mels.py", line 104, in __getitem__
    mel_text = super(FilenamedLoader, self).__getitem__(index)
  File "/exp_fastpitch/FastPitch/tacotron2/data_function.py", line 86, in __getitem__
    mel = self.get_mel(audiopath)
  File "/exp_fastpitch/FastPitch/tacotron2/data_function.py", line 66, in get_mel
    melspec = self.stft.mel_spectrogram(audio_norm)
  File "/exp_fastpitch/FastPitch/common/layers.py", line 119, in mel_spectrogram
    assert(torch.min(y.data) >= -1)
AssertionError
``` 
Audiopath is correct.
What is the purpose of ```--tacotron2-checkpoint```? Is it possible to train FastPitch without training tacotron2?
Should I use ```--text-cleaners basic_cleaners``` on this step?

**Comment by kdorichev** [comment]
@dmitrytyrin If I understand this right, you need to:
 1. update `symbols.py` to correspond to the symbols in your dataset; [see my example](https://github.com/kdorichev/text2speech/blob/master/common/text/symbols.py).
 1. write whatever cleaner you need for your dataset; see [`russian_cleaner`](https://github.com/kdorichev/text2speech/blob/da5be6cbee82b8fe25c0b259a498aac0985d880a/common/text/cleaners.py#L104) in my example.

**Comment by kdorichev** [comment]
@dmitrytyrin If you only need to extract mel spectrograms, you do not need a trained Tacotron2 (TT2) model -- it is used for durations extraction. But to train a FastPitch model in other language, yes you do need a trained TT2 model. IMHO. Working on it myself.

**Comment by dmitrytyrin** [comment]
@kdorichev, thank you! 
I've tried with basic_cleaners and got the same error.
Ok, I need to train Tacotron2 first...
