### ISSUE TITLE
[PyTorch/WaveGlow] NaN loss after 80 epochs

### ISSUE THREAD

**Issue by Charlottecuc** [NVIDIA/DeepLearningExamples#694]
Related to **Model/Framework(s)** 
*PyTorch/Tacotron2/WaveGlow*

**Describe the bug**
Hi. I tried to train the WaveGlow model and encountered `Loss is NaN` problem after 80 epoches. 

**To Reproduce**
`python3 -m multiproc train.py -m WaveGlow -o ./output/ -lr 1e-4 --epochs 1501 -bs 8 --segment-length 8000 --weight-decay 0 --grad-clip-thresh 3.4028234663852886e+38 --cudnn-enabled --cudnn-benchmark --log-file nvlog.json --amp`
I have changed audio parameters such as the sampling rate, filter-length, hop-length, win-length, mel-fmin and mel-fmax in all places. I also changed the stft.py according to https://github.com/NVIDIA/tacotron2/issues/125#issuecomment-500083326 becuase of cpu memory issue.

DLL 2020-09-21 20:06:34.624410 - PARAMETER output : ./output/ 
DLL 2020-09-21 20:06:34.624515 - PARAMETER dataset_path : ./ 
DLL 2020-09-21 20:06:34.624560 - PARAMETER model_name : WaveGlow 
DLL 2020-09-21 20:06:34.624597 - PARAMETER log_file : nvlog4.json 
DLL 2020-09-21 20:06:34.624633 - PARAMETER anneal_steps : None 
DLL 2020-09-21 20:06:34.624671 - PARAMETER anneal_factor : 0.1 
DLL 2020-09-21 20:06:34.624707 - PARAMETER epochs : 1501 
DLL 2020-09-21 20:06:34.624742 - PARAMETER epochs_per_checkpoint : 20 
DLL 2020-09-21 20:06:34.624776 - PARAMETER checkpoint_path : ./output/checkpoint_WaveGlow_80.pt 
DLL 2020-09-21 20:06:34.624813 - PARAMETER resume_from_last : False 
DLL 2020-09-21 20:06:34.624849 - PARAMETER dynamic_loss_scaling : True 
DLL 2020-09-21 20:06:34.624882 - PARAMETER amp : True 
DLL 2020-09-21 20:06:34.624915 - PARAMETER cudnn_enabled : True 
DLL 2020-09-21 20:06:34.624949 - PARAMETER cudnn_benchmark : True 
DLL 2020-09-21 20:06:34.624982 - PARAMETER disable_uniform_initialize_bn_weight : False 
DLL 2020-09-21 20:06:34.625014 - PARAMETER use_saved_learning_rate : False 
DLL 2020-09-21 20:06:34.625045 - PARAMETER learning_rate : 0.0001 
DLL 2020-09-21 20:06:34.625077 - PARAMETER weight_decay : 0.0 
DLL 2020-09-21 20:06:34.625109 - PARAMETER grad_clip_thresh : 3.4028234663852886e+38 
DLL 2020-09-21 20:06:34.625147 - PARAMETER batch_size : 8 
DLL 2020-09-21 20:06:34.625179 - PARAMETER grad_clip : 5.0 
DLL 2020-09-21 20:06:34.625211 - PARAMETER load_mel_from_disk : False 
DLL 2020-09-21 20:06:34.625248 - PARAMETER training_files : filelists/yige/audio_text_train_filelist.txt 
DLL 2020-09-21 20:06:34.625281 - PARAMETER validation_files : filelists/yige/audio_text_val_filelist.txt 
DLL 2020-09-21 20:06:34.625318 - PARAMETER text_cleaners : ['transliteration_cleaners'] 
DLL 2020-09-21 20:06:34.625355 - PARAMETER max_wav_value : 32768.0 
DLL 2020-09-21 20:06:34.625388 - PARAMETER sampling_rate : 24000 
DLL 2020-09-21 20:06:34.625420 - PARAMETER filter_length : 2048 
DLL 2020-09-21 20:06:34.625461 - PARAMETER hop_length : 300 
DLL 2020-09-21 20:06:34.625493 - PARAMETER win_length : 1200 
DLL 2020-09-21 20:06:34.625524 - PARAMETER mel_fmin : 80.0 
DLL 2020-09-21 20:06:34.625557 - PARAMETER mel_fmax : 7600.0 
DLL 2020-09-21 20:06:34.625589 - PARAMETER rank : 0 
DLL 2020-09-21 20:06:34.625620 - PARAMETER world_size : 4 
DLL 2020-09-21 20:06:34.625652 - PARAMETER dist_url : tcp://localhost:23456 
DLL 2020-09-21 20:06:34.625683 - PARAMETER group_name : group_name 
DLL 2020-09-21 20:06:34.625717 - PARAMETER dist_backend : nccl 
DLL 2020-09-21 20:06:34.625749 - PARAMETER bench_class :  
DLL 2020-09-21 20:06:34.625780 - PARAMETER model_name : Tacotron2_PyT 

**Expected behavior**
I have already tried the method offered in https://github.com/NVIDIA/DeepLearningExamples/issues/236 , but the loss was still increasing after epoch 80 and reached positive 7 at epoch 82, which is abnormal. 

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3):
Container was not used.
Pytorch version: 1.2.0

* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB):
Four T4.
Cuda compilation tools, release 10.0, V10.0.130

**Comment by GrzegorzKarchNV** [comment]
Hi @Charlottecuc , could you please update your local repo and check if the issue still occurs? We've updated the repo recently. Even if that doesn't help, we'll at least have a common base for further investigation.

**Comment by ioannist** [comment]
> Hi @Charlottecuc , could you please update your local repo and check if the issue still occurs? We've updated the repo recently. Even if that doesn't help, we'll at least have a common base for further investigation.

Just pulled a repo and got the same error at epoch 67

DLL 2020-10-30 14:07:59.656565 - (67, 36) glob_iter/iters_per_epoch : 12498/186 
Traceback (most recent call last):
  File "train.py", line 554, in <module>
    main()
  File "train.py", line 488, in main
    raise Exception("loss is NaN")
Exception: loss is NaN

**Comment by ioannist** [comment]
@GrzegorzKarchNV  I commented out the raise exception line to see what it would happen. Training goes on but loss is reported as NaN for all subsequent epochs. I captured the switch from number-> NaN in the log below

```
DLL 2020-10-30 14:53:19.375011 - (67, 8) train_iter_time : 0.7504771050007548 
DLL 2020-10-30 14:53:19.377231 - (67, 9) glob_iter/iters_per_epoch : 2985/186 
DLL 2020-10-30 14:53:19.587047 - (67, 9) train_loss : -4.368749618530273 
DLL 2020-10-30 14:53:20.127721 - (67, 9) train_items_per_sec : 21319.20591993759 
DLL 2020-10-30 14:53:20.127814 - (67, 9) train_iter_time : 0.7504969959991286 
DLL 2020-10-30 14:53:20.130266 - (67, 10) glob_iter/iters_per_epoch : 2986/186 
DLL 2020-10-30 14:53:20.340461 - (67, 10) train_loss : -3.372781991958618 
DLL 2020-10-30 14:53:20.882277 - (67, 10) train_items_per_sec : 21276.057506022466 
DLL 2020-10-30 14:53:20.883179 - (67, 10) train_iter_time : 0.7520190239883959 
DLL 2020-10-30 14:53:20.884491 - (67, 11) glob_iter/iters_per_epoch : 2987/186 
DLL 2020-10-30 14:53:21.096695 - (67, 11) train_loss : nan 
DLL 2020-10-30 14:53:21.630547 - (67, 11) train_items_per_sec : 21445.91147235352 
DLL 2020-10-30 14:53:21.630639 - (67, 11) train_iter_time : 0.7460629510023864 
DLL 2020-10-30 14:53:21.632713 - (67, 12) glob_iter/iters_per_epoch : 2988/186 
DLL 2020-10-30 14:53:21.838978 - (67, 12) train_loss : nan 
DLL 2020-10-30 14:53:22.369732 - (67, 12) train_items_per_sec : 21708.865208755902 
DLL 2020-10-30 14:53:22.369824 - (67, 12) train_iter_time : 0.7370260880124988 
DLL 2020-10-30 14:53:22.371903 - (67, 13) glob_iter/iters_per_epoch : 2989/186 
DLL 2020-10-30 14:53:22.578487 - (67, 13) train_loss : nan 
DLL 2020-10-30 14:53:23.108442 - (67, 13) train_items_per_sec : 21723.02166350764 
DLL 2020-10-30 14:53:23.108534 - (67, 13) train_iter_time : 0.7365457829873776 
DLL 2020-10-30 14:53:23.110684 - (67, 14) glob_iter/iters_per_epoch : 2990/186 
DLL 2020-10-30 14:53:23.317522 - (67, 14) train_loss : nan 
DLL 2020-10-30 14:53:23.847904 - (67, 14) train_items_per_sec : 21702.928387387532 
DLL 2020-10-30 14:53:23.848047 - (67, 14) train_iter_time : 0.737227700999938 
DLL 2020-10-30 14:53:23.850146 - (67, 15) glob_iter/iters_per_epoch : 2991/186 
DLL 2020-10-30 14:53:24.057277 - (67, 15) train_loss : nan 
DLL 2020-10-30 14:53:24.586656 - (67, 15) train_items_per_sec : 21723.886464914427 
DLL 2020-10-30 14:53:24.586734 - (67, 15) train_iter_time : 0.7365164619986899 
DLL 2020-10-30 14:53:24.588934 - (67, 16) glob_iter/iters_per_epoch : 2992/186 
DLL 2020-10-30 14:53:24.795992 - (67, 16) train_loss : nan 
DLL 2020-10-30 14:53:25.326941 - (67, 16) train_items_per_sec : 21679.8131112151
```

**Comment by ioannist** [comment]
Started training again with --amp activated and all wav files normalized. Got a division by zero error at epoch 38.

```
DLL 2020-10-30 22:47:30.112884 - (38, 87) train_iter_time : 0.7559060430066893 
DLL 2020-10-30 22:47:30.114633 - (38, 88) glob_iter/iters_per_epoch : 11410/306 
DLL 2020-10-30 22:47:30.377361 - (38, 88) train_loss : -3.687452554702759 
Traceback (most recent call last):
  File "train.py", line 555, in <module>
    main()
  File "train.py", line 500, in main
    scaled_loss.backward()
  File "/home/ioannis/anaconda3/envs/waveglow/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/ioannis/anaconda3/envs/waveglow/lib/python3.7/site-packages/apex/amp/handle.py", line 123, in scale_loss
    optimizer._post_amp_backward(loss_scaler)
  File "/home/ioannis/anaconda3/envs/waveglow/lib/python3.7/site-packages/apex/amp/_process_optimizer.py", line 249, in post_backward_no_master_weights
    post_backward_models_are_masters(scaler, params, stashed_grads)
  File "/home/ioannis/anaconda3/envs/waveglow/lib/python3.7/site-packages/apex/amp/_process_optimizer.py", line 135, in post_backward_models_are_masters
    scale_override=(grads_have_scale, stashed_have_scale, out_scale))
  File "/home/ioannis/anaconda3/envs/waveglow/lib/python3.7/site-packages/apex/amp/scaler.py", line 176, in unscale_with_stashed
    out_scale/grads_have_scale,   # 1./scale,
ZeroDivisionError: float division by zero
```

**Comment by ioannist** [comment]
Turns out that the previous issue is a separate one. Is NaN is also thrown with -amp activated (it just happened that in the previous run the zero division error interrupted the training first). I will open a new ticket for the zero error.

In my dataset, I can get "los is NaN" to be thrown in the first epoch if I set the learning rate to 1e-3. I can make the training files available for download if you want to debug.
