### ISSUE TITLE
[DLRM/PyTorch] Docker build error 

### ISSUE THREAD

**Issue by vibhatha** [NVIDIA/DeepLearningExamples#697]
Related to **DLRM/PyTorch** 

`docker build -t nvidia_dlrm_spark -f Dockerfile_spark .` doesn't execute successfully and I get the following error, 

```bash
Processing triggers for libc-bin (2.27-3ubuntu1) ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   196  100   196    0     0    397      0 --:--:-- --:--:-- --:--:--   396

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c apt update &&     apt install -y openjdk-8-jdk &&     curl https://downloads.apache.org/spark/spark-3.0.0/spark-3.0.0-bin-hadoop3.2.tgz -o /opt/spark-3.0.0-bin-hadoop3.2.tgz &&     tar zxf /opt/spark-3.0.0-bin-hadoop3.2.tgz -C /opt/ &&     rm /opt/spark-3.0.0-bin-hadoop3.2.tgz &&     curl https://repo1.maven.org/maven2/ai/rapids/cudf/0.14/cudf-0.14-cuda10-2.jar -o /opt/cudf-0.14-cuda10-2.jar &&     curl https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark_2.12/0.1.0/rapids-4-spark_2.12-0.1.0.jar -o /opt/rapids-4-spark_2.12-0.1.0.jar' returned a non-zero code: 2
```

**Environment**

* Container version: nvcr.io/nvidia/pytorch:20.07-py3
* GPUs in the system: Tesla K80
* CUDA driver version: <DON'T KNOW>

**Comment by tgrel** [comment]
@vibhatha Thank you for submitting this bug report. This is most likely because of changes in versions of public spark binaries. We will look into this in the next few days.

**Comment by vibhatha** [comment]
@tgrel That would be great!. Is this the version used in the MLPerf benchmarks?

**Comment by PerkzZheng** [comment]
@vibhatha 
I would suggest applying the latest version: 
`Spark 3.0.1, rapids-4-spark_2.12-0.3.0-SNAPSHOT.jar, and cudf-0.16-cuda10-1.jar`
change the curl link to : https://www.apache.org/dyn/closer.lua/spark/spark-3.0.1/spark-3.0.1-bin-hadoop2.7.tgz
rapids-spark and cudf jar can be built from https://github.com/NVIDIA/spark-rapids

This works for me.

**Comment by vibhatha** [comment]
@PerkzZheng thank you. Let me check these.

**Comment by vibhatha** [comment]
@PerkzZheng I got this issue when I ran the code. 

```
20/10/23 12:39:04 INFO MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 0 to 172.16.0.143:33638
Exception in thread "map-output-dispatcher-0" java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.github.luben.zstd.util.Native.load(Native.java:108)
	at com.github.luben.zstd.util.Native.load(Native.java:60)
	at com.github.luben.zstd.ZstdOutputStream.<clinit>(ZstdOutputStream.java:15)
	at org.apache.spark.io.ZStdCompressionCodec.compressedOutputStream(CompressionCodec.scala:224)
	at org.apache.spark.MapOutputTracker$.serializeMapStatuses(MapOutputTracker.scala:913)
	at org.apache.spark.ShuffleStatus.$anonfun$serializedMapStatus$2(MapOutputTracker.scala:210)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.ShuffleStatus.withWriteLock(MapOutputTracker.scala:72)
	at org.apache.spark.ShuffleStatus.serializedMapStatus(MapOutputTracker.scala:207)
	at org.apache.spark.MapOutputTrackerMaster$MessageLoop.run(MapOutputTracker.scala:457)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
client_loop: send disconnect: Broken pipe
```
Are you familiar with this issue?

**Comment by mkfilipiuk** [comment]
Hi @vibhatha,

We've fixed the Dockerfile - could you check if building the image works now?

This code is not the one that takes part in MLPerf, but it very similar. You can find the MLPerf code here: https://github.com/mlcommons/training_results_v0.7/tree/master/NVIDIA/benchmarks/dlrm/implementations/pytorch

**Comment by vibhatha** [comment]
@mkfilipiuk Great!!! I will give it a try.
