### ISSUE TITLE
[CUDAOptimized/Fastspeech] Inference with Waveglow broken (`no module named 'glow'`)

### ISSUE THREAD

**Issue by jfsantos** [NVIDIA/DeepLearningExamples#699]
When trying to run inference for waveform generation with FastSpeech, the code is unable to load the Waveglow checkpoint referred in the documentation. The documentation also has a couple of mistakes, described below.

**To Reproduce**
Following the steps in the inference section, it says to install Waveglow as a submodule (which is wrong, since it is not a submodule of this repository). The Waveglow path is hardcoded in `fastspeech/inferences/waveglow_inferencer.py` as `waveglow`, but even editing it to point to `<repo root>/PyTorch/SpeechSynthesis/Tacotron2/waveglow` does not work. Running `generate.py` fails with the following traceback:

```
Traceback (most recent call last):
  File "generate.py", line 169, in <module>
    fire.Fire(generate)
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "generate.py", line 120, in generate
    ckpt_file=hp.waveglow_path, device=device, use_fp16=hp.use_fp16)
  File "/workspace/fastspeech/fastspeech/inferencer/waveglow_inferencer.py", line 44, in __init__
    self.model = torch.load(self.ckpt_file, map_location=self.device)['model']
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 592, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 772, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'glow'
```

**Expected behavior**
Waveglow checkpoint would be properly loaded and a waveform would be generated.

**Comment by andabi** [comment]
@jfsantos This issue has been fixed.
