### ISSUE TITLE
[FastTransformer/Pytorch] TXX, RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by Sun-Knight-Soral** [NVIDIA/DeepLearningExamples#766]
- FastTransformer v3.0
- CUDA 10.2

with TXX, run `bash pytorch/scripts/run_mrpc.sh thsext fp32` get:
```
11/24/2020 18:50:14 - INFO - __main__ -   Use custom BERT encoder for TorchScript
Traceback (most recent call last):
  File "/workdir/fastertransformer/build/pytorch/run_glue.py", line 383, in <module>
    main()
  File "/workdir/fastertransformer/build/pytorch/run_glue.py", line 359, in main
    enc_ = torch.jit.trace(enc, (fake_inp, fake_mask))
  File "/usr/local/conda/lib/python3.6/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/usr/local/conda/lib/python3.6/site-packages/torch/jit/_trace.py", line 966, in trace_module
    _module_class,
  File "/usr/local/conda/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/conda/lib/python3.6/site-packages/torch/jit/_trace.py", line 327, in _check_trace
    copied_dict[name] = _clone_inputs(data)
  File "/usr/local/conda/lib/python3.6/site-packages/torch/jit/_trace.py", line 160, in _clone_inputs
    )(args)
  File "/usr/local/conda/lib/python3.6/site-packages/torch/autograd/function.py", line 282, in _map
    return type(obj)(mapped)
  File "/usr/local/conda/lib/python3.6/site-packages/torch/autograd/function.py", line 278, in <genexpr>
    mapped = (_map(x) for x in obj)
  File "/usr/local/conda/lib/python3.6/site-packages/torch/autograd/function.py", line 274, in _map
    return fn(obj)
  File "/usr/local/conda/lib/python3.6/site-packages/torch/jit/_trace.py", line 149, in clone_input
    .clone(memory_format=torch.preserve_format)
RuntimeError: CUDA error: invalid device function
```
However, with T4, it works.

**Comment by byshiue** [comment]
Do you run the docker image we recommend?

**Comment by Sun-Knight-Soral** [comment]
No, i will try, close it.
