### ISSUE TITLE
[FasterTransformer3.0/Pytorch] Translation with FasterTransformer3.0 on PyTorch demo model file fails to load

### ISSUE THREAD

**Issue by yuanzhedong** [NVIDIA/DeepLearningExamples#817]
Related to **FasterTransformer/Pytorch** 
*(e.g. GNMT/PyTorch or FasterTransformer/All)*

**Describe the bug**

the downloaded transformer model can't be loaded with error:

```
Traceback (most recent call last):
  File "pytorch/load.py", line 37, in <module>
    fields, model, model_opt = load_test_model(opt, args)
  File "/app/build/pytorch/utils/translation_model.py", line 80, in load_test_model
    map_location=lambda storage, loc: storage)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 585, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 245, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ../caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old.
```
**To Reproduce**
I'm trying to follow the readme and use docker withh pytorch 1.5
```
python pytorch/run_translation.py --batch_size 128 --beam_size 4 --model_type decoding_ext --data_type fp32
```
Seems due to opennmt-py requires pytorch==1.6?

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): pytorch:20.03-py3
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): 1080Ti
* CUDA driver version (e.g. 418.67):10.2

**Comment by yuanzhedong** [comment]
switched to 3.1
