### ISSUE TITLE
[MaskRCNN/Pytorch] train_benchmark.sh RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by jzhang82119** [NVIDIA/DeepLearningExamples#836]
See the debugging message below.

bash -x scripts/train_benchmark.sh -tf32

+ test -f /etc/shinit_v2
+ source /etc/shinit_v2
+++ sed -n 's/^NVRM.*Kernel Module *\([^() ]*\).*$/\1/p' /proc/driver/nvidia/version
+++ sed 's/^$/unknown/'
++ NV_DRIVER_VERS=450.80.02
++ export _CUDA_COMPAT_PATH=/usr/local/cuda/compat
++ _CUDA_COMPAT_PATH=/usr/local/cuda/compat
+++ hostname
++ _CUDA_COMPAT_CHECKFILE=/usr/local/cuda/compat/.450.80.02.6b7d7ebf5f6a.checked
++ _CUDA_COMPAT_REALLIB=/usr/local/cuda/compat/lib.real
++ _CUDA_COMPAT_SYMLINK=/usr/local/cuda/compat/lib
++ '[' -n 450.80.02 -a -e /dev/nvidiactl -a '!' -e /usr/local/cuda/compat/.450.80.02.6b7d7ebf5f6a.checked ']'
++ unset _CUDA_COMPAT_CHECKFILE
++ unset _CUDA_COMPAT_REALLIB
++ unset _CUDA_COMPAT_SYMLINK
+ '[' -z '' ']'
+ return
+ GPU=8
+ GLOBAL_BATCH=32
+ CONFIG=configs/e2e_mask_rcnn_R_50_FPN_1x.yaml
+ RESULTS=/results
+ LOGFILE=/results/joblog.log
+ DTYPE=-tf32
+ '[' -d /results ']'
+ python -m torch.distributed.launch --nproc_per_node=8 tools/train_net.py --config-file configs/e2e_mask_rcnn_R_50_FPN_1x.yaml --skip-test SOLVER.BASE_LR 0.04 SOLVER.MAX_ITER 3665 SOLVER.STEPS '(30000, 40000)' SOLVER.IMS_PER_BATCH 32 DTYPE -tf32 OUTPUT_DIR /results
+ tee /results/joblog.log

Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 247, in main
    backend="nccl", init_method="env://"
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 424, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/train_net.py', '--local_rank=7', '--config-file', 'configs/e2e_mask_rcnn_R_50_FPN_1x.yaml', '--skip-test', 'SOLVER.BASE_LR', '0.04', 'SOLVER.MAX_ITER', '3665', 'SOLVER.STEPS', '(30000, 40000)', 'SOLVER.IMS_PER_BATCH', '32', 'DTYPE', '-tf32', 'OUTPUT_DIR', '/results']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1731, in barrier
    work = _default_pg.barrier()
RuntimeError: CUDA error: unspecified launch failure

**Comment by sharathts** [comment]
From the log 'RuntimeError: Address already in use'

Run ps aux | grep python | awk '{ print $2 }' | xargs kill -9
Before running the training script.

Also, you shouldn't add `-` before `tf32`

**Comment by jzhang82119** [comment]
I make sure this is a clean before running the script. 
scripts/train_benchmark.sh tf32


Now I am getting the following error now.




bash -x scripts/train_benchmark.sh tf32
+ test -f /etc/shinit_v2
+ source /etc/shinit_v2
+++ sed -n 's/^NVRM.*Kernel Module *\([^() ]*\).*$/\1/p' /proc/driver/nvidia/version
+++ sed 's/^$/unknown/'
++ NV_DRIVER_VERS=450.80.02
++ export _CUDA_COMPAT_PATH=/usr/local/cuda/compat
++ _CUDA_COMPAT_PATH=/usr/local/cuda/compat
+++ hostname
++ _CUDA_COMPAT_CHECKFILE=/usr/local/cuda/compat/.450.80.02.bcb13658806c.checked
++ _CUDA_COMPAT_REALLIB=/usr/local/cuda/compat/lib.real
++ _CUDA_COMPAT_SYMLINK=/usr/local/cuda/compat/lib
++ '[' -n 450.80.02 -a -e /dev/nvidiactl -a '!' -e /usr/local/cuda/compat/.450.80.02.bcb13658806c.checked ']'
++ unset _CUDA_COMPAT_CHECKFILE
++ unset _CUDA_COMPAT_REALLIB
++ unset _CUDA_COMPAT_SYMLINK
+ '[' -z '' ']'
+ return
+ GPU=8
+ GLOBAL_BATCH=32
+ CONFIG=configs/e2e_mask_rcnn_R_50_FPN_1x.yaml
+ RESULTS=/results
+ LOGFILE=/results/joblog.log
+ DTYPE=tf32
+ '[' -d /results ']'
+ python -m torch.distributed.launch --nproc_per_node=8 tools/train_net.py --config-file configs/e2e_mask_rcnn_R_50_FPN_1x.yaml --skip-test SOLVER.BASE_LR 0.04 SOLVER.MAX_ITER 3665 SOLVER.STEPS '(30000, 40000)' SOLVER.IMS_PER_BATCH 32 DTYPE tf32 OUTPUT_DIR /results
+ tee /results/joblog.log
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1731, in barrier
    work = _default_pg.barrier()
RuntimeError: CUDA error: unspecified launch failure
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1731, in barrier
    work = _default_pg.barrier()
RuntimeError: CUDA error: unspecified launch failure
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1731, in barrier
    work = _default_pg.barrier()
RuntimeError: Connection reset by peer
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1731, in barrier
    work = _default_pg.barrier()
RuntimeError: CUDA error: unspecified launch failure
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/train_net.py', '--local_rank=7', '--config-file', 'configs/e2e_mask_rcnn_R_50_FPN_1x.yaml', '--skip-test', 'SOLVER.BASE_LR', '0.04', 'SOLVER.MAX_ITER', '3665', 'SOLVER.STEPS', '(30000, 40000)', 'SOLVER.IMS_PER_BATCH', '32', 'DTYPE', 'tf32', 'OUTPUT_DIR', '/results']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1731, in barrier
    work = _default_pg.barrier()
RuntimeError: CUDA error: unspecified launch failure
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1731, in barrier
    work = _default_pg.barrier()
RuntimeError: Broken pipe
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1731, in barrier
    work = _default_pg.barrier()
RuntimeError: Broken pipe
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1731, in barrier
    work = _default_pg.barrier()
RuntimeError: **Broken pipe**
++ cat /results/joblog.log
++ grep -F 'maskrcnn_benchmark.trainer INFO: Total training time'
++ tail -n 1
++ awk '-F(' '{print $2}'
++ awk '-F s ' '{print $1}'
++ egrep -o '[0-9.]+'
+ time=
++ cat /results/joblog.log
++ grep -F 'maskrcnn_benchmark.trainer INFO: Total training time'
++ tail -n 1
+ statement=
++ echo 1.0 32
++ awk '{ printf "%f", $2 * $3 / $1 }'
+ calc=0.000000
+ echo 'Training perf is: 0.000000 FPS'
Training perf is: 0.000000 FPS

**Comment by ptrblck** [comment]
@jzhang82119 
`RuntimeError: CUDA error: unspecified launch failure` could point towards a broken CUDA setup. Assuming you are using the docker container to train this model, you could try to compile an run the CUDA samples as well as NCCL-test. If these are working fine, use a single `DataLoader` worker in the script, which might yield a better error message, and remove the DDP part of the model to isolate the failure further.

**Comment by sharathts** [comment]
@jzhang82119 Please let us know if you are building on the NGC container and following step 3 and 4 on the quick start guide.

**Comment by jzhang82119** [comment]
When I have ECC enabled, I have no error.
When I have ECC disabled, I got that error.

Below are the steps.

![image](https://user-images.githubusercontent.com/49737178/110038326-34dae000-7d05-11eb-8aff-45e62ca9d95d.png)

**Comment by jzhang82119** [comment]
do you guys always have ECC enabled when doing the benchmarking?

**Comment by sharathts** [comment]
@jzhang82119 Can you replace https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Segmentation/MaskRCNN/pytorch/Dockerfile#L15 with 21.02 container?

21.02 works with ECC disabled.

**Comment by jzhang82119** [comment]
got the following error when trying to build this container.

bash scripts/docker/build.sh
Sending build context to Docker daemon  7.402MB
Step 1/10 : ARG FROM_IMAGE_NAME=nvcr.io/nvidia/pytorch:21.02-py3
Step 2/10 : FROM ${FROM_IMAGE_NAME}
 ---> e52a2ed9c61e
Step 3/10 : RUN pip install --upgrade --no-cache-dir pip  && pip install --no-cache-dir       mlperf-compliance==0.0.10       opencv-python==3.4.1.15                                                        git+https://github.com/NVIDIA/dllogger       yacs
 ---> Running in d94b2fd8a2dd
Collecting pip
  Downloading pip-21.0.1-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
Successfully installed pip-21.0.1
Collecting git+https://github.com/NVIDIA/dllogger
  Cloning https://github.com/NVIDIA/dllogger to /tmp/pip-req-build-1433_l6l
  Running command git clone -q https://github.com/NVIDIA/dllogger /tmp/pip-req-build-1433_l6l
Requirement already satisfied: mlperf-compliance==0.0.10 in /opt/conda/lib/python3.8/site-packages (0.0.10)
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.1.15
ERROR: No matching distribution found for opencv-python==3.4.1.15
The command '/bin/sh -c pip install --upgrade --no-cache-dir pip  && pip install --no-cache-dir       mlperf-compliance==0.0.10       opencv-python==3.4.1.15       git+https://github.com/NVIDIA/dllogger       yacs' returned a non-zero code: 1

**Comment by sharathts** [comment]
With 21.02 the opencv-python installation in the docker file can be removed.

**Comment by jzhang82119** [comment]
I am able to build new docker image.

Now I am getting some new error when running benchmark.

bash -x scripts/train_benchmark.sh tf32
+ test -f /etc/shinit_v2
+ source /etc/shinit_v2
+++ sed -n 's/^NVRM.*Kernel Module *\([^() ]*\).*$/\1/p' /proc/driver/nvidia/version
+++ sed 's/^$/unknown/'
++ NV_DRIVER_VERS=450.102.04
++ export _CUDA_COMPAT_PATH=/usr/local/cuda/compat
++ _CUDA_COMPAT_PATH=/usr/local/cuda/compat
+++ hostname
++ _CUDA_COMPAT_CHECKFILE=/usr/local/cuda/compat/.450.102.04.27f20f58fabe.checked
++ _CUDA_COMPAT_REALLIB=/usr/local/cuda/compat/lib.real
++ _CUDA_COMPAT_SYMLINK=/usr/local/cuda/compat/lib
++ '[' -n 450.102.04 -a -e /dev/nvidiactl -a '!' -e /usr/local/cuda/compat/.450.102.04.27f20f58fabe.checked ']'
+++ cat /sys/module/mlx5_core/version
++ DETECTED_MOFED=5.2-2.2.0
++ dpkg --compare-versions 5.2-2.2.0 lt 4.9
++ unset _CUDA_COMPAT_CHECKFILE
++ unset _CUDA_COMPAT_REALLIB
++ unset _CUDA_COMPAT_SYMLINK
+ '[' -z '' ']'
+ return
+ GPU=8
+ GLOBAL_BATCH=32
+ CONFIG=configs/e2e_mask_rcnn_R_50_FPN_1x.yaml
+ RESULTS=/results
+ LOGFILE=/results/joblog.log
+ DTYPE=tf32
+ '[' -d /results ']'
+ python -m torch.distributed.launch --nproc_per_node=8 tools/train_net.py --config-file configs/e2e_mask_rcnn_R_50_FPN_1x.yaml --skip-test SOLVER.BASE_LR 0.04 SOLVER.MAX_ITER 3665 SOLVER.STEPS '(30000, 40000)' SOLVER.IMS_PER_BATCH 32 DTYPE tf32 OUTPUT_DIR /results
+ tee /results/joblog.log
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2419, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: CUDA error: unspecified launch failure
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2419, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: CUDA error: unspecified launch failure
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2419, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: CUDA error: unspecified launch failure
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2419, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: CUDA error: unspecified launch failure
Traceback (most recent call last):
  File "tools/train_net.py", line 297, in <module>
    main()
  File "tools/train_net.py", line 249, in main
    synchronize()
  File "/workspace/object_detection/maskrcnn_benchmark/utils/comm.py", line 46, in synchronize
    dist.barrier()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2419, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: CUDA error: unspecified launch failure
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/train_net.py', '--local_rank=7', '--config-file', 'configs/e2e_mask_rcnn_R_50_FPN_1x.yaml', '--skip-test', 'SOLVER.BASE_LR', '0.04', 'SOLVER.MAX_ITER', '3665', 'SOLVER.STEPS', '(30000, 40000)', 'SOLVER.IMS_PER_BATCH', '32', 'DTYPE', 'tf32', 'OUTPUT_DIR', '/results']' returned non-zero exit status 1.
**Killing subprocess 400
Killing subprocess 401
Killing subprocess 402
Killing subprocess 403
Killing subprocess 404
Killing subprocess 405
Killing subprocess 406
Killing subprocess 407**
++ cat /results/joblog.log
++ grep -F 'maskrcnn_benchmark.trainer INFO: Total training time'
++ tail -n 1
++ awk '-F(' '{print $2}'
++ awk '-F s ' '{print $1}'
++ egrep -o '[0-9.]+'
+ time=
++ cat /results/joblog.log
++ grep -F 'maskrcnn_benchmark.trainer INFO: Total training time'
++ tail -n 1
+ statement=
++ echo 1.0 32
++ awk '{ printf "%f", $2 * $3 / $1 }'
+ calc=0.000000
+ echo 'Training perf is: 0.000000 FPS'
Training perf is: 0.000000 FPS

**Comment by sharathts** [comment]
Is this still with ECC off?
Can you check for ECC errors with `nvidia-smi -q -d ECC` ?
