### ISSUE TITLE
[UNet_Industrial/TensorFlow] unable to run scripts f.e. ./scripts/UNet_1GPU.sh 

### ISSUE THREAD

**Issue by alexnovik** [NVIDIA/DeepLearningExamples#853]
Related to **UNet_Industrial/TensorFlow** 

**Describe the bug**
Traceback (most recent call last):
  File "/workspace/unet_industrial/scripts/../main.py", line 33, in <module>
    from utils import hvd_utils
  File "/workspace/unet_industrial/utils/__init__.py", line 24, in <module>
    from utils import cmdline_helper
  File "/workspace/unet_industrial/utils/cmdline_helper.py", line 24, in <module>
    from datasets import known_datasets
  File "/workspace/unet_industrial/datasets/__init__.py", line 24, in <module>
    from datasets.dagm2007 import DAGM2007_Dataset
  File "/workspace/unet_industrial/datasets/dagm2007.py", line 40, in <module>
    from dllogger import Logger
ImportError: cannot import name 'Logger'

**To Reproduce**
1. Follow each step in quick start guide
2. run script ./scripts/UNet_1GPU.sh /results /data 1

**Expected behavior**
Errors above

**Environment**
Please provide at least:
* Container version:
NVIDIA Release 20.06-tf1 (build 13409399)
TensorFlow Version 1.15.2

* GPUs in the system: 
8x Tesla T4

* CUDA version:
11.0
* Cuda Driver:
418.181.07

**Comment by pribalta** [comment]
@alexnovik , could you try installing dllogger from https://github.com/NVIDIA/dllogger?

`pip install dllogger` should do the trick
