### ISSUE TITLE
[PyTorch/LanguageModeling/BERT] fail to download dataset for SST

### ISSUE THREAD

**Issue by lazykyama** [NVIDIA/DeepLearningExamples#854]
Related to **PyTorch/LanguageModeling/BERT** 
(Note that it's just my confirmation. There might be similar issues on others.)

**Describe the bug**

When I ran a script, `data/create_datasets_from_start.sh`, I encountered following error. I guess it should be related to https://github.com/tensorflow/datasets/issues/2926, and, to resolve this issue, it might be ok to update the version of `download_glue_data.py` be downloaded at https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/data/GLUEDownloader.py#L39.

* Current: https://gist.githubusercontent.com/W4ngatang/60c2bdb54d156a41194446737ce03e2e/raw/17b8dd0d724281ed7c3b2aeeda662b92809aadd5/download_glue_data.py
* Newer: https://gist.githubusercontent.com/W4ngatang/60c2bdb54d156a41194446737ce03e2e/raw/1502038877f6a88c225a34450793fbc3ea87eaba/download_glue_data.py

```
Working Directory: /path/to/working/dir/
Action: download
Dataset Name: sst-2

Directory Structure:
{ 'download': '/path/to/working/dir//download',
  'extracted': '/path/to/working/dir//extracted',
  'formatted': '/path/to/working/dir//formatted_one_article_per_line',
  'hdf5': '/path/to/working/dir//hdf5_lower_case_1_seq_len_512_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5',
  'sharded': '/path/to/working/dir//sharded_training_shards_256_test_shards_256_fraction_0.1',
  'tfrecord': '/path/to/working/dir//tfrecord_lower_case_1_seq_len_512_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5'}

Downloading and extracting SST...
Traceback (most recent call last):
  File "/workspace/bert/data/bertPrep.py", line 363, in <module>
    main(args)
  File "/workspace/bert/data/bertPrep.py", line 60, in main
    downloader.download()
  File "/workspace/bert/data/Downloader.py", line 45, in download
    self.download_glue(self.dataset_name)
  File "/workspace/bert/data/Downloader.py", line 82, in download_glue
    downloader.download(task_name)
  File "/workspace/bert/data/GLUEDownloader.py", line 44, in download
    download_glue_data.main(
  File "/path/to/working/dir//download/glue/download_glue_data.py", line 137, in main
    download_and_extract(task, args.data_dir)
  File "/path/to/working/dir//download/glue/download_glue_data.py", line 47, in download_and_extract
    urllib.request.urlretrieve(TASK2PATH[task], data_file)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/conda/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/conda/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**To Reproduce**
1. Launch docker container based on NGC's PyTorch container `nvcr.io/nvidia/pytorch:20.12-py3`.
    - sudo docker run --gpus=all --rm -it -v $(pwd):/ws nvcr.io/nvidia/pytorch:20.12-py3 
2. Run a script like `bash data/create_datasets_from_start.sh`

**Expected behavior**
No error happens.

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): `nvcr.io/nvidia/pytorch:20.12-py3`
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): TITAN X (Pascal)
* CUDA driver version (e.g. 418.67): 455.45.01

**Comment by swethmandava** [comment]
Thanks for the find. Can you send a PR? @lazykyama

**Comment by lazykyama** [comment]
Thanks for checking. Of course. I will send a PR for this issue later.

**Comment by sharathts** [comment]
Thanks for the PR @lazykyama. It will be merged shortly. Closing the bug, feel free to reopen if you have any more questions.
