### ISSUE TITLE
resnet50v1.5 Training/Inference on Imagenet throws an error of 'Unknown args passed'

### ISSUE THREAD

**Issue by riohib** [NVIDIA/DeepLearningExamples#942]
Related to **Resnet50v1.5/Imagenet** 
*PyTorch*

**Describe the bug**
Training and inference does not work using the command line arguments provided. `main.py` does not have the flag `--pretrained-weights`, and previously we used to pass in the imagenet directory argument at the end, which now seems to be considered an error!

**To Reproduce**
While trying to train the resnet50v1.5 model on imagenet we get the following error:

The command used:
`$ python ./multiproc.py --nproc_per_node 4 ./launch.py --model resnet50 --precision AMP --mode convergence --platform DGX1V /imagenet --epochs 90 --mixup 0.0 --workspace ${1:-./} --raport-file raport.json /data/imagenet-data`

Traceback (most recent call last):
  File "./launch.py", line 49, in <module>
    assert len(rest) == 0, f"Unknown args passed: {rest}"
AssertionError: Unknown args passed: ['/data/imagenet-data']

The unknown arg is the path to the imagenet directory.

Moreover, in a separate case after downloading the pretrained model and keeping it in the directory we get the following error when trying to run inference on resnet50v1.5 on Imagenet:
`Namespace(conv_init='fan_in', last_bn_0_init=False, num_classes=1000, pretrained=False, pretrained_from_file=None)
Traceback (most recent call last):
  File "./main.py", line 604, in <module>
    assert len(rest) == 0, f"Unknown args passed: {rest}"
AssertionError: Unknown args passed: ['--pretrained-weights', '/data/imagenet-data']`

**Expected behavior**
I expect the training and inference commands provided here in the doc to run error free.

**Environment**
Please provide at least:
* Running without contained, by git clone: Pytorch version: pytorch 1.8.1 | py3.8_cuda11.1_cudnn8.0.5_0
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB):
* CUDA driver version  py3.8_cuda11.1_cudnn8.0.5_0.

**Comment by asulecki** [comment]
Hi,

Recently we improved the API for pretrained models, but didn't update the docs tet, sorry about that.

Can you please try '--pretrained-from-file <filename>' or in case of using our checkpoints, just '--pretrained'?

Andrzej

**Comment by riohib** [comment]
Hello again, 
Thanks for the quick response. I think I figured out the validation. Anyway, the following command worked for validation from a file (and --pretrained also worked for validation from container). 

`python ./main.py --arch resnet50 --evaluate --epochs 1 --pretrained-from-file /data/imagenet-data nvidia_resnet50_200821.pth.tar -b 64`

I wanted to mention that it the code runs when we have the path to the imagenet directory right after `--pretrained-from-file` flag, and we have to include the model/weight-file after the path to imagenet directory, as you can see from the command above. I had to go through the traceback to figure this out. I am not sure if this is expected behavior or not, but it wasn't obvious to me.

Also, even though everything runs okay, some warning is thrown at the start regarding some DALI deprecation.

`Namespace(conv_init='fan_in', last_bn_0_init=False, num_classes=1000, pretrained=False, pretrained_from_file='nvidia_resnet50_200821.pth.tar')
=> loading pretrained weights from 'nvidia_resnet50_200821.pth.tar'
/home/users/rohib/anaconda3/envs/nv-imagenet/lib/python3.8/site-packages/nvidia/dali/ops.py:627: DeprecationWarning: WARNING: `coin_flip` is now deprecated. Use `random.coin_flip` instead.
  op_instances.append(_OperatorInstance(input_set, self, **kwargs))
/home/users/rohib/anaconda3/envs/nv-imagenet/lib/python3.8/site-packages/nvidia/dali/ops.py:627: DeprecationWarning: WARNING: `file_reader` is now deprecated. Use `readers.file` instead.
In DALI 1.0 all readers were moved into a dedicated :mod:`~nvidia.dali.fn.readers`
submodule and renamed to follow a common pattern. This is a placeholder operator with identical
functionality to allow for backward compatibility.
  op_instances.append(_OperatorInstance(input_set, self, **kwargs))
/home/users/rohib/anaconda3/envs/nv-imagenet/lib/python3.8/site-packages/nvidia/dali/ops.py:627: DeprecationWarning: WARNING: `image_decoder` is now deprecated. Use `decoders.image` instead.
In DALI 1.0 all decoders were moved into a dedicated :mod:`~nvidia.dali.fn.decoders`
submodule and renamed to follow a common pattern. This is a placeholder operator with identical
functionality to allow for backward compatibility.
  op_instances.append(_OperatorInstance(input_set, self, **kwargs))
read 1281167 files from 1000 directories
/home/users/rohib/anaconda3/envs/nv-imagenet/lib/python3.8/site-packages/nvidia/dali/plugin/pytorch.py:166: Warning: Please do not use `fill_last_batch` and use `last_batch_policy` instead.
  _DaliBaseIterator.__init__(self,
/home/users/rohib/anaconda3/envs/nv-imagenet/lib/python3.8/site-packages/nvidia/dali/ops.py:627: DeprecationWarning: WARNING: `file_reader` is now deprecated. Use `readers.file` instead.
In DALI 1.0 all readers were moved into a dedicated :mod:`~nvidia.dali.fn.readers`
submodule and renamed to follow a common pattern. This is a placeholder operator with identical
functionality to allow for backward compatibility.
  op_instances.append(_OperatorInstance(input_set, self, **kwargs))
/home/users/rohib/anaconda3/envs/nv-imagenet/lib/python3.8/site-packages/nvidia/dali/ops.py:627: DeprecationWarning: WARNING: `image_decoder` is now deprecated. Use `decoders.image` instead.
In DALI 1.0 all decoders were moved into a dedicated :mod:`~nvidia.dali.fn.decoders`
submodule and renamed to follow a common pattern. This is a placeholder operator with identical
functionality to allow for backward compatibility.
  op_instances.append(_OperatorInstance(input_set, self, **kwargs))
read 50000 files from 1000 directories
/home/users/rohib/anaconda3/envs/nv-imagenet/lib/python3.8/site-packages/nvidia/dali/plugin/pytorch.py:166: Warning: Please do not use `fill_last_batch` and use `last_batch_policy` instead.
  _DaliBaseIterator.__init__(self,
DLL 2021-05-24 15:55:16.907157 - PARAMETER data : /data/users2/rohib/github/imagenet-data  data_backend : dali-cpu  interpolation : bilinear  arch : resnet50  workers : 5  epochs : 1  run_epochs : -1  early_stopping_patience : -1  image_size : None  batch_size : 64  optimizer_batch_size : -1  lr : 0.1  lr_schedule : step  end_lr : 0  warmup : 0  label_smoothing : 0.0  mixup : 0.0  optimizer : sgd  momentum : 0.9  weight_decay : 0.0001  bn_weight_decay : False  rmsprop_alpha : 0.9  rmsprop_eps : 0.001  nesterov : False  print_freq : 10  resume : None  static_loss_scale : 1  dynamic_loss_scale : False  prof : -1  amp : False  seed : None  gather_checkpoints : False  raport_file : experiment_raport.json  evaluate : True  training_only : False  save_checkpoints : True  checkpoint_filename : checkpoint.pth.tar  workspace : ./  memory_format : nchw  use_ema : None  augmentation : None  distributed : False  local_rank : 0  gpu : 0  world_size : 1 
DLL 2021-05-24 15:55:16.907862 - PARAMETER model.num_classes : 1000  model.last_bn_0_init : False  model.conv_init : fan_in  model.pretrained_from_file : nvidia_resnet50_200821.pth.tar  model.pretrained : False 
 ! Weight decay NOT applied to BN parameters `
