### ISSUE TITLE
[Tacotron2, WaveGlow/Pytorch] ERROR: Failed to run TTS inference pipeline with fp16

### ISSUE THREAD

**Issue by guyqaz** [NVIDIA/DeepLearningExamples#943]
Related to **SpeechSynthesis/Tacotron2/tensorrt**

**Describe the bug**
I followed the guide 'Tacotron2 + WaveGlow Inference Using TensorRT '
https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/Tacotron2/tensorrt
I have exported Tacotron2 and Waveglow to TensortRT engine.  When running inference pipeline with fp16 with script:

python tensorrt/inference_trt.py -i phrases/phrase.txt --encoder output/encoder_fp16.engine --decoder output/decoder_iter_fp16.engine --postnet output/postnet_fp16.engine --waveglow output/waveglow_fp16.engine -o output/ --fp16

Run Tacotron2 Encoder, Decoder, Postnet done but get error when running WaveGlow  

**Error**
Running Tacotron2 Encoder
Running Tacotron2 Decoder
Stopping after 779 decoder steps
Running Tacotron2 Postnet
Tacotron2 Postnet done
Running WaveGlow
[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input__0
[TensorRT] ERROR: Parameter check failed at: engine.cpp::isShapeBinding::1835, condition: bindingIndex >= 0 && bindingIndex < getNbBindings()
[TensorRT] ERROR: Parameter check failed at: engine.cpp::getBindingDimensions::1851, condition: bindIndex >= 0 && bindIndex < getNbBindings()
[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input__1
[TensorRT] ERROR: Parameter check failed at: engine.cpp::isShapeBinding::1835, condition: bindingIndex >= 0 && bindingIndex < getNbBindings()
[TensorRT] ERROR: Parameter check failed at: engine.cpp::getBindingDimensions::1851, condition: bindIndex >= 0 && bindIndex < getNbBindings()
[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: output__0
Traceback (most recent call last):
  File "tensorrt/inference_trt.py", line 386, in <module>
    main()
  File "tensorrt/inference_trt.py", line 351, in main
    audios = infer_waveglow_trt(waveglow, waveglow_context, mel, measurements, args.fp16)
  File "tensorrt/inference_trt.py", line 293, in infer_waveglow_trt
    run_trt_engine(waveglow_context, waveglow, waveglow_tensors)
  File "/workspace/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/tensorrt/trt_utils.py", line 54, in run_trt_engine
    context.execute_v2(bindings=bindings)
TypeError: execute_v2(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.IExecutionContext, bindings: List[int]) -> bool

**Environment**
Please provide at least:
* GPUs in the system: Tesla V100-SXM2-32GB
* CUDA driver version: 10.2

**Comment by guyqaz** [comment]
Name of input, output WaveGlow is wrong. I solved it.

**Comment by sqhuang** [comment]
came cross same error here

for someone still struggling here

you may get fixed by modifing `tensorrt/inference_trt.py` 

```
284 
285     waveglow_tensors = {
286         "inputs" :
287         #{'input__0': mel, 'input__1': z},
288         {'mel': mel, 'z': z},
289         "outputs" :
290         #{'output__0': audios}
291         {'audio': audios}
292     }
293     print("Running WaveGlow")
294     with MeasureTime(measurements, "waveglow_time"):
295         run_trt_engine(waveglow_context, waveglow, waveglow_tensors)
296 
297     return audios
298 

```
