### ISSUE TITLE
[Model/Framework] What is the problem?

### ISSUE THREAD

**Issue by ZJLi2013** [NVIDIA/DeepLearningExamples#950]
Related to **Model/Framework(s)** 

sample from tf2/efficientNet 

**Describe the bug**

when launch the training, at the 1 epoch.  it reports:

```sh
[1,0]<stdout>:Epoch 1/500
[1,0]<stderr>:WARNING:tensorflow:The operation `tf.image.convert_image_dtype` will be skipped since the input and output dtypes are identical.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "main.py", line 54, in <module>
[1,0]<stderr>:    runner.train()
[1,0]<stderr>:  File "/workspace/runtime/runner.py", line 217, in train
[1,0]<stderr>:    history = self.model.fit(
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
[1,0]<stderr>:    tmp_logs = self.train_function(iterator)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
[1,0]<stderr>:    result = self._call(*args, **kwds)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 871, in _call
[1,0]<stderr>:    self._initialize(args, kwds, add_initializers_to=initializers)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
[1,0]<stderr>:    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
[1,0]<stderr>:    graph_function, _ = self._maybe_define_function(args, kwargs)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
[1,0]<stderr>:    graph_function = self._create_graph_function(args, kwargs)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
[1,0]<stderr>:    func_graph_module.func_graph_from_py_func(
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
[1,0]<stderr>:    func_outputs = python_func(*func_args, **func_kwargs)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
[1,0]<stderr>:    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
[1,0]<stderr>:    raise e.ag_error_metadata.to_exception(e)
[1,0]<stderr>:TypeError: in user code:
[1,0]<stderr>:
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
[1,0]<stderr>:        return step_function(self, iterator)
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
[1,0]<stderr>:        outputs = model.distribute_strategy.run(run_step, args=(data,))
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
[1,0]<stderr>:        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
[1,0]<stderr>:        return self._call_for_each_replica(fn, args, kwargs)
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
[1,0]<stderr>:        return fn(*args, **kwargs)
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
[1,0]<stderr>:        outputs = model.train_step(data)
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:757 train_step
[1,0]<stderr>:        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:498 minimize
[1,0]<stderr>:        return self.apply_gradients(grads_and_vars, name=name)
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/horovod/_keras/__init__.py:143 apply_gradients
[1,0]<stderr>:        results = super(self.__class__, self).apply_gradients(*args, **kwargs)
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:625 apply_gradients
[1,0]<stderr>:        apply_state = self._prepare(var_list)
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:880 _prepare
[1,0]<stderr>:        self._prepare_local(var_device, var_dtype, apply_state)
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/rmsprop.py:164 _prepare_local
[1,0]<stderr>:        super(RMSprop, self)._prepare_local(var_device, var_dtype, apply_state)
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimiz[1,0]<stderr>:er_v2/optimizer_v2.py:886 _prepare_local
[1,0]<stderr>:        lr_t = array_ops.identity(self._decayed_lr(var_dtype))
[1,0]<stderr>:    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:943 _decayed_lr
[1,0]<stderr>:        lr_t = math_ops.cast(lr_t(local_step), var_dtype)
[1,0]<stderr>:    /workspace/utils/learning_rate.py:51 __call__
[1,0]<stderr>:        lr = self._lr_schedule(step)
[1,0]<stderr>:
[1,0]<stderr>:    TypeError: 'dict' object is not callable
[1,0]<stderr>:

```

**To Reproduce**

run training with B0, TF32 mode on 1 GPU card, 

 the `convergence_training.sh` is exactly as  8xA100 sample, except updating  `horovod -np 1` as only one GPU

```sh
./scripts/B0/training/TF32/convergence_training.sh
```

**Expected behavior**

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3):   nvcr.io/nvidia/tensorflow         21.05-tf2-py3
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB):  A6000
* CUDA driver version (e.g. 418.67):   11.3

**Comment by subhankar-ghosh** [comment]
Hey @ZJLi2013 , This is an issue with Horovod and it will be fixed in 21.06 container. You can use 21.02 or 21.03 container for now, this issue does not exist in these containers.
