### ISSUE TITLE
[FastPitch/PyTorch] No module named 'nvidia_dlprof_pytorch_nvtx'

### ISSUE THREAD

**Issue by shangeth** [NVIDIA/DeepLearningExamples#988]
Related to **FastPitch/PyTorch** 

**Describe the bug**
I want to train FastPitch for a custom dataset, I set up everything as mentioned in the [Readme](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/FastPitch#training-process).
1. Build and run the FastPitch PyTorch NGC container.
2. Download and preprocess the dataset.
But when I start train with `bash scripts/train.sh` or `CUDA_VISIBLE_DEVICES=1,2,3 AMP=true NUM_GPUS=1 BS=128 GRAD_ACCUMULATION=2 EPOCHS=10 bash scripts/train.sh`
It returns 
```
Traceback (most recent call last):
  File "train.py", line 39, in <module>
    import nvidia_dlprof_pytorch_nvtx as pyprof
ModuleNotFoundError: No module named 'nvidia_dlprof_pytorch_nvtx'
Killing subprocess 134655
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train.py', '--local_rank=0', '--cuda', '-o', './output/', '--log-file', './output/nvlog.json', '--dataset-path', 'LJSpeech-1.1', '--training-files', '/root/shangeth/p1-tts-experiments-fastPitch/DeepLearningExamples/PyTorch/SpeechSynthesis/FastPitch/VAIDataset/filelists/vai_train.txt', '--validation-files', '/root/shangeth/p1-tts-experiments-fastPitch/DeepLearningExamples/PyTorch/SpeechSynthesis/FastPitch/VAIDataset/filelists/vai_val.txt', '--pitch-mean-std-file', '/root/shangeth/p1-tts-experiments-fastPitch/DeepLearningExamples/PyTorch/SpeechSynthesis/FastPitch/VAIDataset/pitch_char_stats__vai_train.json', '--epochs', '10', '--epochs-per-checkpoint', '100', '--warmup-steps', '1000', '-lr', '0.1', '-bs', '128', '--optimizer', 'lamb', '--grad-clip-thresh', '1000.0', '--dur-predictor-loss-scale', '0.1', '--pitch-predictor-loss-scale', '0.1', '--weight-decay', '1e-6', '--gradient-accumulation-steps', '2', '--amp']' returned non-zero exit status 1.
```

**To Reproduce**
As given in [Readme](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/FastPitch#training-process), except custom dataset. 

**Expected behavior**
Train the model with the given dataset path.

**Environment**
* Container version (fastpitch:latest):
* GPUs in the system: (4x NVIDIA A100-40GB):
* CUDA driver version (465.19.01):

**Comment by rave974** [comment]
```
pip install nvidia-pyindex
pip install nvidia-dlprof[pytorch]
```

**Comment by zsh01** [comment]
Hi @shangeth, @rave974

thanks for reporting and fixing this! In the updated FastPitch v1.1 code this import is wrapped with `try/catch`.

**Comment by alancucki** [comment]
Hi @shangeth, @rave974

thanks for reporting and fixing this! In the updated FastPitch v1.1 code this import is wrapped with try/catch.
